### ISSUE TITLE
ability to remove file by SHA

### ISSUE THREAD

**Issue by dmd** [rtyley/bfg-repo-cleaner#100]
Back when I was stupid, I committed `someimportantfile`, but I created it wrong, and it's *HUGE*.

Then, later, I _replaced_ that file with one with the exact same name, but smaller.

I'd like BFG to be able to remove the old one, while keeping the new one.

**Comment by rtyley** [comment]
The BFG already supports removing files by their Git hash id (similar, but not the same as, a simple SHA-1 hash of file contents). If you run the BFG without arguments, it gives a full list of options, including `--strip-blobs-with-ids`:

```
  -bi <blob-ids-file> | --strip-blobs-with-ids <blob-ids-file>
        strip blobs with the specified Git object ids
```

As I said, a file's Git hash id is not the _same_ as the SHA-1 hash of file contents, but you can calculate it just as easily using the [`git hash-object`](http://git-scm.com/docs/git-hash-object) command:

```
$ git hash-object README.md 
746cb1288b3e26d01ac320f7d0b7b869b8ae1801
$ sha1sum README.md
ef17ee000e14cf3f938836e2aad1c3cf5229129b  README.md
```

I hope that helps - feel free to support the BFG at https://www.bountysource.com/teams/bfg-repo-cleaner

**Comment by dmd** [comment]
Aha! Thanks!
