### ISSUE TITLE
Why it's not allowed to run command in different git folder?

### ISSUE THREAD

**Issue by kenorb** [rtyley/bfg-repo-cleaner#101]
I've been in different folder than the git root and  I run the command:

    bfg --delete-files settings.php

but I've had the following error:

> Aborting : /git/root/trunk/sites/default is not a valid Git repository.

which confused me a bit, but after some time I figure it out that I have to run the same command in git root repo folder.

Is it an expected behaviour?

**Comment by rtyley** [comment]
So your git repository was at `/git/root`?

The BFG does expect you to either be in the top level folder of your repository, or for you to specify the path to your repository as the last command-line arg. Anything else begins to get ambiguous as soon as git submodules are involved.
