### ISSUE TITLE
Undo feature

### ISSUE THREAD

**Issue by algarecu** [rtyley/bfg-repo-cleaner#103]
It would be nice if, “in case of messing up the repository history” (specially on Github), this tool had an option to undo the last command issued. I guess this could be using the content in the file object-id-map.old-new.txt under bfg-report folder it generates? Otherwise, where would you start looking?

**Comment by rtyley** [comment]
> It would be nice if, “in case of messing up the repository history” (specially on Github), this tool had an option to undo the last command issued.

The usage instructions do tell you to make a back-up of your repo before you start any destructive operation: https://rtyley.github.io/bfg-repo-cleaner/#usage - if you've made this backup, you should be fine.

> I guess this could be using the content in the file object-id-map.old-new.txt under bfg-report folder it generates?

If you don't have a backup, you could use the `object-id-map.old-new.txt` file to work out what your old branch refs were, and then manually reset them.

**Comment by fastfading** [comment]
oh   ,  I should not try this tool,  when I saw this , it is already to late.

**Comment by javabrett** [comment]
@fastfading just reclone your remote repo and you have undone what BFG did in your local clone.

**Comment by javabrett** [comment]
Take a look at https://rtyley.github.io/bfg-repo-cleaner/#protected-commits for your options on (un)protecting branches using `--protect-blobs-from`.

In order to persist your rewritten history you will need to be able to push back all branches, including master, at least once.

**Comment by minipunch** [comment]
+1 for the undo command

Or emphasize the fact that you need to 1) make a backup manually of the repo and 2) to not push any changes after running it

I ran bfg, and it said I had some protected stuff and to delete the folder and commit that manually... so I did... and I pushed it by habit... and now it pushed like 563 duplicated commits into the repository and it appears there is no easy way to undo it....

**Comment by gunjan075** [comment]
@rtyley how i can revert everything from object-id-map.old-new.txt. 
--strip-biggest-blobs 100 seems to have a problem

**Comment by gunjan075** [comment]
--strip-biggest-blobs  should be thrown away from bfg @rtyley
