### ISSUE TITLE
Binary file replacer (truncate file size to zero)?

### ISSUE THREAD

**Issue by dweiss** [rtyley/bfg-repo-cleaner#120]
Hello. Where do I need to poke around in the source code to implement something that does not *remove* binary files (arbitrary filename pattern, say *.jar, *.zip) but truncates their file size to zero?

The reason for this is basically that we want to keep references to the binary filenames (for historical reasons), but reduce repository size.

I know nothing about scala, which makes modifying the source a bit difficult. Sigh.

**Comment by rtyley** [comment]
You probably want a mixture of `FileDeleter` and `BlobReplacer`:

https://github.com/rtyley/bfg-repo-cleaner/blob/44191f38a/bfg-library/src/main/scala/com/madgag/git/bfg/cleaner/treeblobs.scala#L29-L43

 Least effort is probably just changing the implementation of `FileDeleter.apply()` to create a suitable `TreeBlobEntry` (rather than just filtering the unwanted ones out, as it does now). See `BlobReplacer.apply` for an example of that - good luck!

**Comment by dweiss** [comment]
Thanks Roberto. I managed to tweak text replacer without knowing Scala... This is dumb like hell, but does the job.

{code}
diff --git a/bfg-library/src/main/scala/com/madgag/git/bfg/cleaner/BlobTextModifier.scala b/bfg-library/src/main/scala/com/madgag/git/bfg/cleaner/BlobTextModifier.scala
index 30f581d..371168f 100644
--- a/bfg-library/src/main/scala/com/madgag/git/bfg/cleaner/BlobTextModifier.scala
+++ b/bfg-library/src/main/scala/com/madgag/git/bfg/cleaner/BlobTextModifier.scala
@@ -54,13 +54,9 @@ trait BlobTextModifier extends TreeBlobModifier {
         loader         <- Some(threadLocalObjectDBResources.reader().open(e.objectId))
         if loader.getSize < sizeThreshold
         streamResource <- Some(Resource.fromInputStream(loader.openStream()))
-        charset        <- charsetDetector.charsetFor(e, streamResource)
-        reader         <- Some(streamResource.reader(charset))
-        lines = reader.lines(includeTerminator = true)
-        if lines.exists(isDirty)
       } yield {
         val b = new ByteArrayOutputStream(loader.getSize.toInt)
-        lines.view.map(lineCleaner).foreach(line => b.write(line.getBytes(charset)))
         val oid = threadLocalObjectDBResources.inserter().insert(OBJ_BLOB, b.toByteArray)
         e.copy(objectId = oid)
       }
{code}
