### ISSUE TITLE
Git unable to unlink after cleaning with bfg

### ISSUE THREAD

**Issue by polykrom** [rtyley/bfg-repo-cleaner#122]
Hi,

I come to you because i have an issue using bfg, i've successfully cleaned my local repo with bfg but when i try to sudo git reflog expire --expire=now --all && git gc --prune=now --aggressive i get unlink impossible because permission denied...

Don't understand why i don't have the privileges ...

Any helps would be great

Thanks

François

`sudo java -jar bfg.jar --convert-to-git-lfs *.zip --no-blob-protection
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Using repo : /Users/polykrom/Documents/Server/vagrant-local/www/www.blaamy/htdocs/.git

Found 0 objects to protect
Found 8 tag-pointing refs : refs/tags/pantheon_live_1, refs/tags/pantheon_live_2, refs/tags/pantheon_live_3, ...
Found 7 commit-pointing refs : HEAD, refs/heads/master, refs/remotes/origin/HEAD, ...

Protected commits
-----------------

You're not protecting any commits, which means the BFG will modify the contents of even *current* commits.

This isn't recommended - ideally, if your current commits are dirty, you should fix up your working copy and commit that, check that your build still works, and only then run the BFG to clean up your history.

Cleaning
--------

Found 157 commits
Cleaning commits:       100% (157/157)
Cleaning commits completed in 12,441 ms.

Updating 2 Refs
---------------

	Ref                          Before     After   
	------------------------------------------------
	refs/heads/master          | 59d36adc | 5eccf672
	refs/remotes/origin/master | 737986a3 | 0bda09bd

Updating references:    100% (2/2)
...Ref update completed in 171 ms.

Commit Tree-Dirt History
------------------------

	Earliest                                              Latest
	|                                                          |
	..............................................DDDDDDDDDDDDDD

	D = dirty commits (file tree fixed)
	m = modified commits (commit message or parents changed)
	. = clean commits (no changes to file tree)

	                        Before     After   
	-------------------------------------------
	First modified commit | 126ce045 | a8563beb
	Last dirty commit     | 59d36adc | 5eccf672

Changed files
-------------

	Filename                                                    Before & After     
	-------------------------------------------------------------------------------
	20151110_blaamy_5666f62b20f5c9298151208152427_archive.zip | bacc517d ⇒ 09ddf042
	go_pricing.zip                                            | 9194bddb ⇒ 0b491a17
	js_composer.zip                                           | b007ea13 ⇒ 5a645098
	k-elements.zip                                            | 968a6b97 ⇒ 172e5b19
	revslider.zip                                             | 58fa5eb3 ⇒ bf34551b

In total, 47 object ids were changed. Full details are logged here:

	/Users/polykrom/Documents/Server/vagrant-local/www/www.blaamy/htdocs.bfg-report/2015-12-23/04-06-05

BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive

Has the BFG saved you time?  Support the BFG on BountySource:  https://j.mp/fund-bfg

iMacdeFrancois:htdocs polykrom$ sudo git reflog expire --expire=now --all && git gc --prune=now --aggressive
Counting objects: 22334, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (21720/21720), done.
Writing objects: 100% (22334/22334), done.
Total 22334 (delta 7411), reused 14900 (delta 0)
warning: unable to unlink .git/objects/01/a63769783bb7e049712cd57cd6a2cedd964986: Permission denied
warning: unable to unlink .git/objects/02/c2199c17c6a6a177af5149716db254492ead93: Permission denied
warning: unable to unlink .git/objects/02/e332a81ec53b99fb2468bda6cd3e07eac6097c: Permission denied
warning: unable to unlink .git/objects/09/ddf04227e264eec0103be4c76024974224f005: Permission denied
warning: unable to unlink .git/objects/0b/491a1738cdb4c2780fe46c7f8fc3f58c36db97: Permission denied
warning: unable to unlink .git/objects/0b/da09bdc316e7e558dc550526f4509cc58c932e: Permission denied
warning: unable to unlink .git/objects/0d/a284dddc8d985cd3e0cd32d4778b22cd679711: Permission denied
warning: unable to unlink .git/objects/14/6d09edaf629e7595b219bbb0f56234305a4596: Permission denied
warning: unable to unlink .git/objects/17/2e5b19ee0a0223a1d463a9b4649f4dc61b0a2a: Permission denied
warning: unable to unlink .git/objects/19/8fb4112001b17e24da6effe8b954fedf62c829: Permission denied
warning: unable to unlink .git/objects/1c/04683a90ea08a508f1172338da86422baa50d4: Permission denied
warning: unable to unlink .git/objects/2a/0576d39a0e8bd42ee734d929dcf4eb5f722787: Permission denied
warning: unable to unlink .git/objects/2b/218b7d5cbcb605ee7f60026776f4435718ff84: Permission denied
warning: unable to unlink .git/objects/2e/add535dff23ece34ce62c6b2267a18993816be: Permission denied
warning: unable to unlink .git/objects/32/c69bedd7ff1979c0955e69407ae333071b27be: Permission denied
warning: unable to unlink .git/objects/38/0b0d1f88d8f2a8222dd87bc33322d15248a60b: Permission denied
warning: unable to unlink .git/objects/39/03c76d8355ee5dcc80ff79b71e455b3f81570b: Permission denied
warning: unable to unlink .git/objects/4b/7eae605eb5b7b5d37e767620fa7888d615e2c4: Permission denied
warning: unable to unlink .git/objects/53/7e358939ea0839dd732ec935be2a63ed25368f: Permission denied
warning: unable to unlink .git/objects/53/dd6a99d80a039d8a062c897e753b13d0818b08: Permission denied
warning: unable to unlink .git/objects/58/b787c2961d9759ce6cdd2de0a27cbb2ba4cad6: Permission denied
warning: unable to unlink .git/objects/5a/645098f4bced92112e121be211d582c3e7e481: Permission denied
warning: unable to unlink .git/objects/5e/ccf67247804c70d10ce93dcb72edd00fe7bb37: Permission denied
warning: unable to unlink .git/objects/60/c98b2bea8ee7df5a2669074904616c737a7d8e: Permission denied
warning: unable to unlink .git/objects/61/bb5022c007997b0095056d377fa72b9fc3112b: Permission denied
warning: unable to unlink .git/objects/68/909fff172652d2620d8e58452f27e1c3bce8c4: Permission denied
warning: unable to unlink .git/objects/68/9536513b169d6af70d5931e18eb495d8f016fe: Permission denied
warning: unable to unlink .git/objects/68/b510aee50b19a8c7ac66faa7b0ca09bdea04e0: Permission denied
warning: unable to unlink .git/objects/6b/d06a3eb4f34e7e37fc4c063100dc9df244760c: Permission denied
warning: unable to unlink .git/objects/72/561daff368990ec6fb2fe1c348c102382684d5: Permission denied
warning: unable to unlink .git/objects/76/a149328735247b4a1e0a70bacffd18dfb038d3: Permission denied
warning: unable to unlink .git/objects/76/f0b3c4170671eafc00e3ccf5ac7130f175e6e4: Permission denied
warning: unable to unlink .git/objects/7c/58ca2c5c36156c88bc85945407f0ff48c81f50: Permission denied
warning: unable to unlink .git/objects/7d/c621eea2bbfaac122737aa5f69fb4aca8a8f84: Permission denied
warning: unable to unlink .git/objects/9a/dbf312e629c1485082c3cd4c9f0a5f07041e94: Permission denied
warning: unable to unlink .git/objects/9c/0313f39cd49670bbc7dd84028eab77bdbb8873: Permission denied
warning: unable to unlink .git/objects/a5/4e92d98cbe32852aa781898a48960bc0d6f04b: Permission denied
warning: unable to unlink .git/objects/a8/563bebc40dce2f2324b917e80f9db1d9e101fe: Permission denied
warning: unable to unlink .git/objects/ae/0479fa3b958cfb2a9645f4e0b8fdd5f9b5bedd: Permission denied
warning: unable to unlink .git/objects/b1/8d6fc295764a305d7718d43f7fd6370009db0e: Permission denied
warning: unable to unlink .git/objects/b1/dd036e0525c0f450259acba9091e37394c4767: Permission denied
warning: unable to unlink .git/objects/b5/72ccffb40bec55fc318b49b0bb8852795f43f8: Permission denied
warning: unable to unlink .git/objects/bf/34551be6e1f26ce797cf8e3da3dfa7c4a2b298: Permission denied
warning: unable to unlink .git/objects/cd/fcf5e0e8fac31e36938fbfa8e170eeb38485b8: Permission denied
warning: unable to unlink .git/objects/d1/2b859483edf65d8bc6eabef704490d8b5cec6c: Permission denied
warning: unable to unlink .git/objects/d3/8e12ce078531516d43ed909a85cf2802dc96c1: Permission denied
warning: unable to unlink .git/objects/d4/ce2a88f31b953f00027efa3f96c0e6bbb1cbb6: Permission denied
warning: unable to unlink .git/objects/e4/dce7a79f46977ab532206200d18bf0b0e8fb99: Permission denied
warning: unable to unlink .git/objects/e6/567786604c877a639f6de0ac50199bd3b8a03a: Permission denied
warning: unable to unlink .git/objects/ec/9d70e1570b333355a58f05067c0837d68f2970: Permission denied
warning: unable to unlink .git/objects/f1/92bada98b735fa00e1e009db9a06cfcf888652: Permission denied
warning: unable to unlink .git/objects/f6/e2b4e26b2f6ed922fbe84326f40e4928e3b052: Permission denied
warning: unable to unlink .git/objects/fa/d6f083b59943f3426c56a1932492b0e5b65f12: Permission denied
Removing duplicate objects: 100% (256/256), done.
warning: unable to unlink .git/objects/17/3cfef9829542df5c8eeabd34c314e51575dce4: Permission denied
warning: unable to unlink .git/objects/20/f720e27cd17eca1adcc5a5f91b18089463c9e4: Permission denied
warning: unable to unlink .git/objects/32/2f418a892b32000bb35d046a7c314cf10a7bdc: Permission denied
warning: unable to unlink .git/objects/3c/771e8a8892f1449d192a87a9c3ad98dfd921e3: Permission denied
warning: unable to unlink .git/objects/41/f5c7c43229d6ebbd36bb0729aed5957e33a700: Permission denied
warning: unable to unlink .git/objects/50/bda6dd78bf563bbcd248f1b3372693fb7c4bac: Permission denied
warning: unable to unlink .git/objects/58/df4ce959122d4d16e465690298276e240db337: Permission denied
warning: unable to unlink .git/objects/59/d36adc319851aba9abdfe3967059112a075eff: Permission denied
warning: unable to unlink .git/objects/71/92957f99f94cf192d867a2f864ad9062259648: Permission denied
warning: unable to unlink .git/objects/8f/405087b31e3f527d6d614bad7537c566f51b66: Permission denied
warning: unable to unlink .git/objects/95/ef6bc254a8dffdfa651dac2f2bf1d3fc6f981f: Permission denied
warning: unable to unlink .git/objects/9a/284897adcc61211bbd8320d747fa8d222b4769: Permission denied
warning: unable to unlink .git/objects/a8/5892f78bfbc06b082171d4e67d676a0f22d006: Permission denied
warning: unable to unlink .git/objects/b0/6d8d5a695d95bd2ea7c82e8400258652e1e0af: Permission denied
warning: unable to unlink .git/objects/bf/c443ade9bc9a61b66bb74c412c4e3eeebfea61: Permission denied
warning: unable to unlink .git/objects/c0/a43138adafe85cf9c4747e92877e04a617a458: Permission denied
warning: unable to unlink .git/objects/c3/ba5749b5e844d5a5a0aceb2f3aa1c2c1f5dbd3: Permission denied
warning: unable to unlink .git/objects/c5/4ef4be3f0167128efb963e0dfd99e233c5a198: Permission denied
warning: unable to unlink .git/objects/d2/24ebe586e856fc9548a5628cb055a473d804fe: Permission denied
warning: unable to unlink .git/objects/d4/c15a44d8032c7c77196e4f5981528fb3937001: Permission denied
warning: unable to unlink .git/objects/df/034874c6a033509631453a0db5f9d4d8962672: Permission denied
warning: unable to unlink .git/objects/e6/53b933d08108fbd42d5f36040dfdee128c12a0: Permission denied
warning: unable to unlink .git/objects/01/a63769783bb7e049712cd57cd6a2cedd964986: Permission denied
warning: unable to unlink .git/objects/02/c2199c17c6a6a177af5149716db254492ead93: Permission denied
warning: unable to unlink .git/objects/02/e332a81ec53b99fb2468bda6cd3e07eac6097c: Permission denied
warning: unable to unlink .git/objects/09/ddf04227e264eec0103be4c76024974224f005: Permission denied
warning: unable to unlink .git/objects/0b/491a1738cdb4c2780fe46c7f8fc3f58c36db97: Permission denied
warning: unable to unlink .git/objects/0b/da09bdc316e7e558dc550526f4509cc58c932e: Permission denied
warning: unable to unlink .git/objects/0d/a284dddc8d985cd3e0cd32d4778b22cd679711: Permission denied
warning: unable to unlink .git/objects/14/6d09edaf629e7595b219bbb0f56234305a4596: Permission denied
warning: unable to unlink .git/objects/17/2e5b19ee0a0223a1d463a9b4649f4dc61b0a2a: Permission denied
warning: unable to unlink .git/objects/19/8fb4112001b17e24da6effe8b954fedf62c829: Permission denied
warning: unable to unlink .git/objects/1c/04683a90ea08a508f1172338da86422baa50d4: Permission denied
warning: unable to unlink .git/objects/2a/0576d39a0e8bd42ee734d929dcf4eb5f722787: Permission denied
warning: unable to unlink .git/objects/2b/218b7d5cbcb605ee7f60026776f4435718ff84: Permission denied
warning: unable to unlink .git/objects/2e/add535dff23ece34ce62c6b2267a18993816be: Permission denied
warning: unable to unlink .git/objects/32/c69bedd7ff1979c0955e69407ae333071b27be: Permission denied
warning: unable to unlink .git/objects/38/0b0d1f88d8f2a8222dd87bc33322d15248a60b: Permission denied
warning: unable to unlink .git/objects/39/03c76d8355ee5dcc80ff79b71e455b3f81570b: Permission denied
warning: unable to unlink .git/objects/4b/7eae605eb5b7b5d37e767620fa7888d615e2c4: Permission denied
warning: unable to unlink .git/objects/53/7e358939ea0839dd732ec935be2a63ed25368f: Permission denied
warning: unable to unlink .git/objects/53/dd6a99d80a039d8a062c897e753b13d0818b08: Permission denied
warning: unable to unlink .git/objects/58/b787c2961d9759ce6cdd2de0a27cbb2ba4cad6: Permission denied
warning: unable to unlink .git/objects/5a/645098f4bced92112e121be211d582c3e7e481: Permission denied
warning: unable to unlink .git/objects/5e/ccf67247804c70d10ce93dcb72edd00fe7bb37: Permission denied
warning: unable to unlink .git/objects/60/c98b2bea8ee7df5a2669074904616c737a7d8e: Permission denied
warning: unable to unlink .git/objects/61/bb5022c007997b0095056d377fa72b9fc3112b: Permission denied
warning: unable to unlink .git/objects/68/909fff172652d2620d8e58452f27e1c3bce8c4: Permission denied
warning: unable to unlink .git/objects/68/9536513b169d6af70d5931e18eb495d8f016fe: Permission denied
warning: unable to unlink .git/objects/68/b510aee50b19a8c7ac66faa7b0ca09bdea04e0: Permission denied
warning: unable to unlink .git/objects/6b/d06a3eb4f34e7e37fc4c063100dc9df244760c: Permission denied
warning: unable to unlink .git/objects/72/561daff368990ec6fb2fe1c348c102382684d5: Permission denied
warning: unable to unlink .git/objects/76/a149328735247b4a1e0a70bacffd18dfb038d3: Permission denied
warning: unable to unlink .git/objects/76/f0b3c4170671eafc00e3ccf5ac7130f175e6e4: Permission denied
warning: unable to unlink .git/objects/7c/58ca2c5c36156c88bc85945407f0ff48c81f50: Permission denied
warning: unable to unlink .git/objects/7d/c621eea2bbfaac122737aa5f69fb4aca8a8f84: Permission denied
warning: unable to unlink .git/objects/9a/dbf312e629c1485082c3cd4c9f0a5f07041e94: Permission denied
warning: unable to unlink .git/objects/9c/0313f39cd49670bbc7dd84028eab77bdbb8873: Permission denied
warning: unable to unlink .git/objects/a5/4e92d98cbe32852aa781898a48960bc0d6f04b: Permission denied
warning: unable to unlink .git/objects/a8/563bebc40dce2f2324b917e80f9db1d9e101fe: Permission denied
warning: unable to unlink .git/objects/ae/0479fa3b958cfb2a9645f4e0b8fdd5f9b5bedd: Permission denied
warning: unable to unlink .git/objects/b1/8d6fc295764a305d7718d43f7fd6370009db0e: Permission denied
warning: unable to unlink .git/objects/b1/dd036e0525c0f450259acba9091e37394c4767: Permission denied
warning: unable to unlink .git/objects/b5/72ccffb40bec55fc318b49b0bb8852795f43f8: Permission denied
warning: unable to unlink .git/objects/bf/34551be6e1f26ce797cf8e3da3dfa7c4a2b298: Permission denied
warning: unable to unlink .git/objects/cd/fcf5e0e8fac31e36938fbfa8e170eeb38485b8: Permission denied
warning: unable to unlink .git/objects/d1/2b859483edf65d8bc6eabef704490d8b5cec6c: Permission denied
warning: unable to unlink .git/objects/d3/8e12ce078531516d43ed909a85cf2802dc96c1: Permission denied
warning: unable to unlink .git/objects/d4/ce2a88f31b953f00027efa3f96c0e6bbb1cbb6: Permission denied
warning: unable to unlink .git/objects/e4/dce7a79f46977ab532206200d18bf0b0e8fb99: Permission denied
warning: unable to unlink .git/objects/e6/567786604c877a639f6de0ac50199bd3b8a03a: Permission denied
warning: unable to unlink .git/objects/ec/9d70e1570b333355a58f05067c0837d68f2970: Permission denied
warning: unable to unlink .git/objects/f1/92bada98b735fa00e1e009db9a06cfcf888652: Permission denied
warning: unable to unlink .git/objects/f6/e2b4e26b2f6ed922fbe84326f40e4928e3b052: Permission denied
warning: unable to unlink .git/objects/fa/d6f083b59943f3426c56a1932492b0e5b65f12: Permission denied`

**Comment by NHellFire** [comment]
You need to run:
sudo git reflog expire --expire=now --all && **sudo** git gc --prune=now --aggressive

**Comment by polykrom** [comment]
Hi !

Thanks for the tip ... Seems it works for one of my remote repo but not for the other , i get the following error message. I don't think it's bfg related but maybe you can help me with this issue.

git push origin master
To ssh://codeserver.dev.6772218a-1527-40f6-b858-deb592b38fdf@codeserver.dev.6772218a-1527-40f6-b858-deb592b38fdf.drush.in:2222/~/repository.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'ssh://codeserver.dev.6772218a-1527-40f6-b858-deb592b38fdf@codeserver.dev.6772218a-1527-40f6-b858-deb592b38fdf.drush.in:2222/~/repository.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

thanks in advance !

François

**Comment by polykrom** [comment]
Re,

Sorry for the newbie request. It works now when pushing with force ...

All is all right ;)

keep the good work !

regards

François
