### ISSUE TITLE
Failed to load class ? warning?

### ISSUE THREAD

**Issue by dubiao** [rtyley/bfg-repo-cleaner#131]
I  meant to execute "bfg --strip-blobs-bigger-than 70M" 
Thanks to your great job that it works perfectly. But also gave me a output as following: 
> $ bfg --strip-blobs-bigger-than 70M
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> 
> Using repo : ****.git
> ....

The "strip"ing job was done. I just wonder what does the warning stand for. 
In addition, I installed bfg via brew: `brew install bfg`

**Comment by javabrett** [comment]
Caused by transient dependency to slf4j-api from jgit, but without an implementation.  Added slf4j-simple to packaging in pull-request #132.
