### ISSUE TITLE
Add usage of --convert-to-git-lfs to the bfg page

### ISSUE THREAD

**Issue by hirose31** [rtyley/bfg-repo-cleaner#142]
`--convert-to-git-lfs` option is awesome! I hope you will add usage on `--convert-to-git-lfs` (step-by-step and how to specify multi file types) option to https://rtyley.github.io/bfg-repo-cleaner/ .
- https://github.com/rtyley/bfg-repo-cleaner/releases/tag/v1.12.5
- https://github.com/rtyley/bfg-repo-cleaner/issues/129

**Comment by javabrett** [comment]
Usage is already on no-arg output:

```
  --convert-to-git-lfs <value>
        extract files with the specified names (eg '*.{zip,mp4}') into Git LFS
```
