### ISSUE TITLE
BFG Tool running without errors but not actually deleting files

### ISSUE THREAD

**Issue by zcicala** [rtyley/bfg-repo-cleaner#144]
I've been playing around with BFG to reduce the size of our repo. When running the bfg tool from the command line everything seems to work fine. It creates a log directory with deleted files and mapping. I can run the prune and gc steps that it recommends without any issue. 

At the end of the process the repo is no smaller and the blobs that BFG claims got deleted are still in the repo. 

>>> java -jar ~/Downloads/bfg-1.12.12.jar --no-blob-protection --strip-blobs-bigger-than 512K ./

>>> git reflog expire --expire=now --all && git gc --prune=now --aggressive

>>> head ..bfg-report/2016-04-12/16-47-27/deleted-files.txt
8afa72875d3013620bb122916bd1ec33a066cbf2 1075353 file_name1.gpx
7656f6464c67f92c48cdbb03ec5a81067c636238 1644202 file_name2.csv
ab68fb197d4479b3b6dec6e85bd5cbaf433a87c5 773236 file_name3.ttf
86c9c0b55ff99c3789bb3ed17daf51bebacba1cb 870631 file_name4@2x.png
70c928943feab0a3a1f97b4f752e9dbc1d8f37fa 950305 file_name5@2x.png
3862d0da43f5902c75e86ff0dd925d8cca601de3 779356 file_name6@2x.png
6effce4b245961cb46e2cf3f4d05bd6c8c182760 908017 file_name7@2x.png
1866b1053dd48fc4d0677f03feb4baf2f67b567c 1353732 file_name8.gif
f0d984f00678504fe073110bb6553049e9678755 1350785 file_name9.gif
af877d286b12b9f79560a938375abe04a15ff405 3214192 file_name10.gif

>>> cat-file -s 8afa72875d3013620bb122916bd1ec33a066cbf2
1075353

I tried the same commands on a brand new repo and everything went as expected. Am I missing something?

**Comment by javabrett** [comment]
What assertions do you make to determine that the repo hasn't shrunk? Are you working in a bare or non-bare repo?

**Comment by zcicala** [comment]
Bare. 
So I was exaggerating when I said there was no change. There was a small change

BEFORE:
```
git count-objects -vH
count: 0
size: 0 bytes
in-pack: 1616184
packs: 1
size-pack: 3.38 GiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

AFER:
```
git count-objects -vH
count: 0
size: 0 bytes
in-pack: 1974752
packs: 1
size-pack: 3.00 GiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes

```

**Comment by zcicala** [comment]
I've figured out the problem. We had a lot of old branches that still pointed to trees with large blobs. Deleting these and rerunning bfg gave me a multi gigabyte reduction.

 I had thought that the --no-blob-protection flag would have addressed this state.

**Comment by javabrett** [comment]
`--no-blob-protection` would normally only remove the protection from `HEAD`.  Not sure what happened with your old branches without details.

**Comment by Hektve87** [comment]
@hektve

**Comment by jahangiranwari** [comment]
We ran into similar issue and it turned out that some branches were duplicates (i.e. one lowercased and another uppercased) which prevented the blobs from being cleaned up. After removing the duplicate branches and running BFG we were able to significantly reduce the repository size.
