### ISSUE TITLE
cannot get basic usage to work

### ISSUE THREAD

**Issue by patakye** [rtyley/bfg-repo-cleaner#150]
i downlaoded the jar file, and made a new repository to test out deleting an old file from history ... here is what i did (on a mac): 

1) make folder called test
2) initialize new local git repository in folder /test/
3) add file A, commit
4) add file B, commit
5) add file C, commit
6) from repo directory, delete file A
7) commit the file deletion 
8) run command:  java -jar ../bfg.jar --delete-files A ./.git from within git repo directory

result is:  
`These are your protected commits, and so their contents will NOT be altered:`
` * commit 3ee73267 (protected by 'HEAD')`
`Cleaning`
`--------`
`Found 4 commits`
`Cleaning commits:       100% (4/4)`
`Cleaning commits completed in 26 ms.`
`BFG aborting: No refs to update - no dirty commits found??`

I want to delete file A, and all history for it .. why can i not do this?

**Comment by javabrett** [comment]
Please post complete BFG output here or as a gist,  the above  is somewhat truncated (object protection census report is missing).  Also, is the test-repo similarly available as a gist or temp repo, pre-BFG execution?

**Comment by patakye** [comment]
here is full output:

ubongs-iphone:test patakye$ java -jar ../bfg-1.12.12.jar --delete-files ckt.cir ./.git

Using repo : /Users/patakye/GIT/test/./.git

Found 3 objects to protect
Found 2 commit-pointing refs : HEAD, refs/heads/master

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

 * commit 3ee73267 (protected by 'HEAD')

Cleaning
--------

Found 4 commits
Cleaning commits:       100% (4/4)
Cleaning commits completed in 26 ms.

BFG aborting: No refs to update - no dirty commits found??



Has the BFG saved you time?  Support the BFG on BountySource:  https://j.mp/fund-bfg

**Comment by patakye** [comment]
test repo can be made exactly from the few steps above

**Comment by patakye** [comment]
add any files A,B,C

**Comment by patakye** [comment]
my understanding is for bfg to delete the history of a file, it simply has to be deleted and commited, then you run the bfg command right? ... this is the main purpose of this tool correct? ... can you tell me simply, how i can remove all history of a particular file?

**Comment by javabrett** [comment]
Example:

`curl https://gist.githubusercontent.com/javabrett/227f276e4eba94e4d483621d6d68b643/raw/45208e577e5107f136837a6ed60943ac9bdd9c75/bfg-simple.sh | bash`

`# cd to that temp git repo directory`

`java -jar ~/git/bfg-repo-cleaner/bfg/target/bfg-1.12.13-SNAPSHOT-remotes/upstream/HEAD-8abe03c.jar -D A`

Output: https://gist.github.com/javabrett/3fa872fc933dcacd5fc1b8ac18a81615

```
Deleted files
-------------

	Filename   Git id        
	-------------------------
	A        | f70f10e4 (2 B)
```

Can you compare?

**Comment by patakye** [comment]
thank you .. your example worked, and then i went back and rechecked until i found that i was trying to delete a file that never existed ... combined that i had a couple commands that truly did nothing and should not have ... i got confused ... now i fixed the script and it works fine.  thanks again

**Comment by The-Penultimate-Defenestrator** [comment]
@patakye You can close this issue if it's solved
