### ISSUE TITLE
Provide mapping from old to new commits

### ISSUE THREAD

**Issue by taerath** [rtyley/bfg-repo-cleaner#181]
Hello,

Would it be feasible for bfg to output a mapping of original commit ids to new commit ids?

I would like to run bfg on a Git repository that was imported from Subversion some time ago. If we ever need to refer to a specific Subversion revision, we have a "mapping" file that just lists each svn revision with the corresponding Git commit id.

However, I believe if I now run bfg on the repository, it will change all the commit ids - making the mapping useless. If there was a way to keep track of what old commit becomes which new commit, we could use this to update the svn rev - git commit mapping.

**Comment by rtyley** [comment]
The BFG does this, it's in the bfg-report as object-id-map.old-new.txt
