### ISSUE TITLE
current version of file remains after delete

### ISSUE THREAD

**Issue by ochompsky** [rtyley/bfg-repo-cleaner#182]
I know how to delete a files history but the last commit remains intact.  How do I delete that too?  

Is the correct approach to delete from git first, then do the history removal?  

This is the command I ran:
`bfg --delete-files file.bat repo.git`

File history is gone.  But the file itself is still there, with the last commit.

**Comment by javabrett** [comment]
See the "your current files are sacred" section of https://rtyley.github.io/bfg-repo-cleaner/ .

Either remove the file from HEAD, or disable blob protection.

**Comment by ochompsky** [comment]
thanks for the quick response.  removed file then ran again.
