### ISSUE TITLE
git-svn fetch gives Invalid revision range after bfg cleanup

### ISSUE THREAD

**Issue by Burdu** [rtyley/bfg-repo-cleaner#185]
I have a git repo in migration from SVN with git-svn.
I use git svn fetch to get the latest commints from SVN. I wanted to push the repo to github, but there were some files in the history larger than 100 MB, so I used bfg repo cleaner to get rid of them

`$ java -jar bfg-1.12.14.jar --strip-blobs-bigger-than 100M`
`BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive
`

`$ git reflog expire --expire=now --all && git gc --prune=now --aggressive
Counting objects: 204963, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (171827/171827), done.
Writing objects: 100% (204963/204963), done.
Total 204963 (delta 91547), reused 106805 (delta 0)`

Now this happens:

`$ git svn fetch -A authors-transform.txt
fatal: Invalid revision range b156a7b66be002c3bf38987ea503f5c852146343
rev-list --pretty=raw --reverse b156a7b66be002c3bf38987ea503f5c852146343..refs/remotes/git-svn --: command returned error: 128`

**Comment by rtyley** [comment]
Hi @Burdu, I can see that you might think this was a bug with the BFG, but it isn't - your best bet is to go to http://stackoverflow.com/

https://github.com/rtyley/bfg-repo-cleaner/blob/master/CONTRIBUTING.md#issues-and-questions

Feel free to leave a comment on this issue linking to the relevant answer/question on StackOverflow.

**Comment by sergiodelacruz** [comment]
I had the same problem. This helped me: https://stackoverflow.com/a/3282594/94484
