### ISSUE TITLE
Just write how to install it.

### ISSUE THREAD

**Issue by srugano** [rtyley/bfg-repo-cleaner#191]
Hi,
It's cool. But for a new user, why not just state on the landing page of the repo how to install this application on their machine ? It's not obvious that it's a jar file meant to be run.

**Comment by mrmartineau** [comment]
@srugano I agree, I had no idea how to properly install it. Luckily I found it on homebrew so I installed it with `brew install bfg`

**Comment by guillaume-chevalier** [comment]
@srugano You might have not seen this `BUILD.md` file which contains the installation instructions: 
https://github.com/rtyley/bfg-repo-cleaner/blob/master/BUILD.md

I almost missed it, I was expecting the instructions to be in the README.md. I would have liked to see that to the README earlier.

**Comment by ppKrauss** [comment]
So...?  There are no UBUNTU `apt install`  for *bfg*?

**Comment by ppKrauss** [comment]
... Please see the "new user" second and **BIG PROBLEM**: there are no link to download  jar file, we need a link as rememberded by https://github.com/rtyley/bfg-repo-cleaner/issues/304

**Comment by ajtruckle** [comment]
I am sorry but I have absolutely no idea what the instructions on the readme file really mean. :(

I never use java. All I want to do is delete some binary files from my repository.

**Comment by ppKrauss** [comment]
Hi   @ajtruckle ,  the instructions are confuse because there are no visible download link... If you dowload `bfg.jar`  you can run it by the intructions of https://rtyley.github.io/bfg-repo-cleaner/  

Check the latest `bfg.jar` download at  http://repo1.maven.org/maven2/com/madgag/bfg/
for example [bfg-1.13.0.jar](http://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar).

The step-by-step is:

1. Download the last  `bfg.jar`
2. open terminal, go to the same directory of the jar file (`cd path`) and run the *bfg*  command... Example *bfg help* command is `java -jar  bfg-1.13.0.jar  --help`.

If  it is running fine, you can follow instructions of http://repo1.maven.org/maven2/com/madgag/bfg/

**Comment by ppKrauss** [comment]
Hi @ajtruckle  seems that you must install Java, that is native for systems like Ubuntu but not for perhaps not for Windows, check with google the easyest way to install Java in your computer. The reliable source for download is https://www.java.com/download/  ... see https://java.com/en/download/help/windows_manual_download.xml

**Comment by ajtruckle** [comment]
@ppKrauss I have installed java.

I can now run the java line you gave me and it shows the help.

I have the bfg-1.13.0.jar file in my repository folder.

if I type bfg --delete-files *.apt it says bfg is not found.

**Comment by ajtruckle** [comment]
ok i have to prefix with java keyword.

**Comment by ppKrauss** [comment]
Hi @ajtruckle, good. Next step is to folow (and **understand**) the instructions at https://rtyley.github.io/bfg-repo-cleaner/  ... Well, the main pieaces to understand are:

* `cd yourPath; git clone --mirror git://example.com/some-big-repo.git` <br/>will create a new sub-directory on   `yourPath` directory... Pleae use the repo name like `https://github.com/FAQGURU/FAQGURU.git`  that is the "clone or download" 
 string at https://github.com/FAQGURU/FAQGURU

* run a *bfg* command. You need to replace `bfg`  by `java -jar bfg-1.13.0.jar`. <br/>Example: try with to delete all files with more tham 1M with  the command <br/>`java -jar bfg-1.13.0.jar --strip-blobs-bigger-than 1M  my-repo.git`<br/> where `my-repo.git` is the name of the new sub-directory created in the item above.

**Comment by the-simian** [comment]
If you're on Windows and you use [scoop](https://scoop.sh/), you can `scoop install bfg` from powershell

**Comment by MikePreston17** [comment]
@ppKrauss Shouldn't `bfg.jar` be put on the $PATH somehow so it can be called from anywhere?  It seems what you're proposing means we have to copy `bfg.jar` to each repository we want to clean before we run it using `java`.

**Comment by johnnyutahh** [comment]
Also: [bfg install via Homebrew-on-Linux seems to work nicely](https://github.com/rtyley/bfg-repo-cleaner/issues/255#issuecomment-606705860).

**Comment by pztrick** [comment]
This is my install script working on Ubuntu 20.04:

```
#!/bin/bash
set -e

# install java
sudo apt -y install default-jre-headless

# fetch latest bfg.jar
sudo wget https://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar -O /usr/local/bin/bfg-latest.jar

# install to /usr/local/bin
echo -e "#!/bin/bash\njava -jar /usr/local/bin/bfg-latest.jar \$@" | sudo tee /usr/local/bin/bfg

# mark executable
sudo chmod +x /usr/local/bin/bfg
```

This is coded to install version `bfg-1.13.0.jar` but perhaps could be improved if anyone knows a link to the latest binary release (e.g. `release-master.jar` or similar).

**Comment by Canderson156** [comment]
I agree with the first original comment. As a git beginner, it took me more than a day to realize that there was a Download button in a small font at the top of the page. I thought I just had to type in the code. I also didn't really know WHERE i was supposed to type this code in. In the local copy of my repository? In the cloned copy I just made? I'm finding the resources available for beginners to do this very lacking and am getting super frustrated.

**Comment by farnaznouraei** [comment]
It is really not clear from the documentation; but there is a download button here: [(https://rtyley.github.io/bfg-repo-cleaner/)]
Once you have` bfg-1.13.0.jar `in your directory you can run `$ java -jar bfg.jar --strip-blobs-bigger-than 100M some-big-repo.git`

**Comment by balcides** [comment]
> @srugano I agree, I had no idea how to properly install it. Luckily I found it on homebrew so I installed it with `brew install bfg`

Bless your soul.

**Comment by gajrajgchouhan** [comment]
Can you guys distribute a executable (like a binary) which doesn't require to install java ?

**Comment by ctrl-f5** [comment]
I, too, had to search and end up in this issue to then realize i need to install java, find a jar to download and then execute it that way... THis should really be the first instruction in the readme.

**Comment by brendanxwhitaker** [comment]
IMO this is definitely still a major issue. Why was it closed?

**Comment by johnnyutahh** [comment]
I too am confused why the java/jar/whatever environment setup/install is not made more clear or more-clearly documented. fwiw, here's how I have historically installed on macOS and Linux (although the Linux install with homebrew is quite unusual and because of this might have bigger issues, like 1+GB of storage space needed to install homebrew only for bfg... ugh).

I frankly have never understood the author's/project.maintainer's apparent (?) refusal to better assist us "Java-sysadmin ignorants," or whatever dynamic is happening. It just makes things unnecessarily hard, imho.

https://github.com/rtyley/bfg-repo-cleaner/issues/255#issuecomment-606705860
https://github.com/rtyley/bfg-repo-cleaner/issues/255#issuecomment-606366455

**Comment by Eloren1** [comment]
Imagine saying that your utility is **faster by 10 - 720 times** than **git-filter-branch** command, when you need to spend a lot more time installing it because developers don't care about other people who have other things to do besides study this horror. So, just use `git-filter-branch`.

**Comment by ppKrauss** [comment]
Is https://github.com/newren/git-filter-repo/ an alternative for bfg-repo-cleaner?

**Comment by kucho** [comment]
> This is coded to install version `bfg-1.13.0.jar` but perhaps could be improved if anyone knows a link to the latest binary release (e.g. `release-master.jar` or similar).

I am a little late to the party, but you could do something like this:

```bash
❯ curl -s https://search.maven.org/solrsearch/select?q=a:bfg | jq '.response.docs[0].latestVersion'
"1.14.0"
```

**Comment by Casey-Hofland** [comment]
HOW THE DO I INSTALL BFG?!?!?!?!?!?!?!?!??!!?!?!?!?!

This is INCREDIBLY frustrating!!!!!!!! PLEASE "Just write how to install it." like the issue asks!

**Comment by langfield** [comment]
@Casey-Hofland Just use `git-filter-repo`, I think it's even endorsed by `git` itself.

**Comment by Casey-Hofland** [comment]
@langfield thanks, I came across it looking for alternatives and I'm going to give it a shot.

So on the `git-filter-repo` it _does_ say that `git` endorses it, but then I came here because of gits own documentation pointing me in this direction:
https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage

But that's on me for relying on `git docs` :')

**Comment by bradygilg** [comment]
For conda users, the 1.14 release can be installed like any other package.  https://anaconda.org/conda-forge/bfg

`conda install conda-forge::bfg`

Miniconda installation instructions are at https://docs.anaconda.com/free/miniconda/miniconda-install/

**Comment by srugano** [comment]
Original issuer here. 8 years later, it still confuse some people how to install this package on Ubuntu particularly since homebrew is not native to Linux. But since we don't have time and resources to fix that, let's stop commenting here unless do the work...

**Comment by clarkritchie** [comment]
Now @ 10 years, LOL.
