### ISSUE TITLE
How to run BFG on a Single Branch?

### ISSUE THREAD

**Issue by mjames-upc** [rtyley/bfg-repo-cleaner#201]
And why the default is to process all branches?  That is extremely undesirable.

**Comment by rtyley** [comment]
The BFG is a simpler, faster alternative to git-filter-branch for cleansing bad data (eg passwords, big files) out of your Git repository history - things that shouldn't exist anywhere in your history, on any branch. That's why it operates on all branches.

If you want something that only acts on one branch, you have a different kind of problem, so you need a different tool.

**Comment by mjames-upc** [comment]
Wow, that's unfortunate.  I have a branch with 100M files which I can not push to github.  So I create a duplicate branch in order to remove those files with bfg to be able to push.  However, since bfg processes all branches, it will corrupt the history of my original branch, making future updates and merges problematic.

**Comment by mjames-upc** [comment]
Seriously it's ridiculous that you don't account for individual branches and intend to rewrite the history of all.  I've got 20 branches here, I don't want to screw up the commit history for each of them, only one.  There has to be a way.

**Comment by rtyley** [comment]
Just to be clear, do you have _multiple_ branches with >100MB files, or is the only branch with big files the one that you want to push to GitHub?

**Comment by mjames-upc** [comment]
Multiple branches with 100M files from remote repo #1 (not github), trying to remove them from a single so I can push/pull that one to/from github without overwriting the history of the original (which will complicate future pulls and merges from remote repo #1).

**Comment by rtyley** [comment]
From my understanding of your problem, I don't think I'd count this as an issue with the BFG, so I'm okay leaving this issue closed. However, I'd recommend you ask a question on StackOverflow, tagged with `git-rewrite-history`, laying out the details of your problem as you've done here - there's a wider audience of question-answering people there, and you'll get a good range of answers

**Comment by mjames-upc** [comment]
Will do, thanks.

**Comment by alucarded** [comment]
I would also like to be able to rewrite history only for one branch when using bfg. It is not an issue, but it would be a very desirable feature.

Right now I am simply cloning fresh repository, using bfg and pushing a single branch to remote.
