### ISSUE TITLE
Remove Immature Political Agenda from a Repo Cleaner

### ISSUE THREAD

**Issue by Sieabah** [rtyley/bfg-repo-cleaner#206]
Really makes you wonder... Maybe make it when you clone not every time you run it.

**Comment by spacekookie** [comment]
I hope it doesn't get removed. Besides, supporting organisations like the ACLU is important!

**Comment by gulbanana** [comment]
not really any different from vim's message asking for donations. if you don't like the messages you can avoid the software.

**Comment by Sieabah** [comment]
@gulbanana It's entirely different than vim asking for donations. Asking for money and promoting a political platform that some may or may not agree with is different. Just because you may agree with it doesn't make it not immature. You can keep it but don't make it show on every run. Limit it to install only or in the same place as credits.

**Comment by yanokwa** [comment]
This was already addressed at https://github.com/rtyley/bfg-repo-cleaner/issues/205. If you don't like the message, feel free to fork or use another tool.
