### ISSUE TITLE
Where do I put bfg.jar?

### ISSUE THREAD

**Issue by TharosTheDragon** [rtyley/bfg-repo-cleaner#212]
I figured I'd have to rename the file I downloaded to bfg.jar. I'm following the [instructions](https://rtyley.github.io/bfg-repo-cleaner/), and when I try to use bfg I get an error.
```
$ java -jar bfg.jar
Error: Unable to access jarfile bfg.jar
```
I guess this may be more of a Git Bash question than a bfg question, but where do I put bfg.jar to make it accessible to Java? It works if it's in my project's working directory but since bfg isn't specific to my project I'd like it in a more global location.

I'm using Windows 10 64-bit.

**Comment by javabrett** [comment]
Just put it anywhere you like and provide the full path to it in the command line.

**Comment by TharosTheDragon** [comment]
There's no special jar path like there is for executables so that you don't have to type it all out?

**Comment by javabrett** [comment]
No.  The BFG docs suggest creating an alias (or wrapper-script) `bfg` which can hide the location of `bfg.jar`.

**Comment by TharosTheDragon** [comment]
Thanks.

**Comment by off99555** [comment]
The simple way to create alias that work for me is to make a new folder named `C:\Aliases`.
Put `bfg.jar` in there.
Create a batch file `bfg.bat`.
Inside the file, you paste this content:
```
@echo off
echo.
java -jar %~dp0\bfg-1.13.0.jar %*
```
Then you can call `bfg` inside command prompt.
