### ISSUE TITLE
--replace-text ignores some strings even if they are in the git history

### ISSUE THREAD

**Issue by vgrange** [rtyley/bfg-repo-cleaner#227]
I need to remove some IP addresses from my git history (for example 111.222.111.222). I put these IP addresses, one by line, in a passwords.txt file. Then I run `java -jar bfg-1.12.15.jar --replace-text passwords.txt project.git`. Seems like BFG does not detect the IPs at all: `BFG aborting: No refs to update - no dirty commits found??`

My HEAD commit is clean, IPs are no longer present in the current code, only in the history.

I think the issue is with the dots "." special characters in the IP address. When I just use "111" in passwords.txt without any dot, BFG now finds correctly many dirty commits.

I tried various syntaxes to get the dot properly working (single quotes, double quotes, backslashes) nothing helped. Please help :) How I am supposed to get dots correctly managed?

If I am correct that the dot is the issue, that's quite an issue: if passwords including a dot have been silently ignored for everybody.... I hope I'm wrong and I'm missing something.

I've been looking for some examples of `--replace-text` online but actually they are not so many, and none with a dot.

**Comment by vgrange** [comment]
Well after testing more strings, I also found simple strings, without any dot, which are not detected. Good news, my issues has nothing to do with dots, I will change the subject, and test some more examples.

**Comment by javabrett** [comment]
Are you able to reproduce the problem in a trivial Git repository that can be shared somewhere?  And what does your `passwords.txt` look like?

**Comment by vgrange** [comment]
Hi, sorry I had to move on due to time constraints, I eventually removed the whole git history instead of sensitive data only. Will close the ticket now.
