### ISSUE TITLE
[Question] What if it's not feasible to ask everyone to clone the repo anew?

### ISSUE THREAD

**Issue by dep** [rtyley/bfg-repo-cleaner#229]
"At this point, you're ready for everyone to ditch their old copies of the repo and do fresh clones of the nice, new pristine data. It's best to delete all old clones, as they'll have dirty history that you don't want to risk pushing back into your newly cleaned repo."

What if this isn't an option? What would the general workflow be for my team to integrate this maintenance branch back in to their current work?  Unfortunately, given the size of the team, asking everyone to clone a new copy of the repo isn't feasible.

Thanks!

**Comment by javabrett** [comment]
It would be good to understand what the parameters are for "asking everyone to clone a new copy of the repo isn't feasible" ... size of the team, size of the repo, communications challenges??

The general workflow goes something like this:

- Any developers _without_ outstanding work-in-progress (e.g. in their local repos, or in local/remote branches that are _not_ going to be cleaned and retained) should just dump their local repos and make a fresh clone.  The old clone of the pre-re-written repo is full of a completely different history now, with bulk etc. and is dangerous to retain - you don't ever want to see any of this history merged-in.
- Developers _with_ WIP need to do one of a few options:
-- Make a fresh clone, generate a patch-set for their WIP commits, reapply/rebase onto new/rewritten branches. (simplest)
-- Update their clone, reset branches the rebase WIP commits onto the new branches.  After WIP is completed and pushed, it is always better to then get a fresh clone, to eliminate any bad history coming back via merges.

**Comment by dep** [comment]
Thank you for the reply. Good advice.

**Comment by javabrett** [comment]
Perhaps this question-issue can be closed?
