### ISSUE TITLE
The Greatest Thing Since Sliced Bread

### ISSUE THREAD

**Issue by mitchellkrogza** [rtyley/bfg-repo-cleaner#239]
This is not an issue but merely a compliment on an absolutely fabulous tool. 

Thank you SOOOO much for creating this. I had a repo which had grown to a whopping 3.8 Gb 😮  running of a 5 Mbps line from South Africa was just making it impossible to work with.

![screen shot 2017-09-26 at 4 29 00 pm](https://user-images.githubusercontent.com/9961541/30962110-c850b40c-a448-11e7-9ae4-f557946212a5.png)

With BFG Cleaner I was able to run a simple one liner like this.

`java -jar bfg-1.12.15.jar --delete-files "{continue.txt,result.txt,list,hosts,*active.txt,percentage.txt,inactive.txt,invalid.txt,combined*.txt,*.zip,hosts.deny,domains.list,hosts.windows,superhosts.deny,execution.log,install.log,potentially*.txt,inactive*.txt}" Ultimate.Hosts.Blacklist.git/`

and VOILA !!!

![screen shot 2017-09-28 at 1 05 20 pm](https://user-images.githubusercontent.com/9961541/30963473-ceb09e5c-a44d-11e7-8c64-8cb54252a020.png)

BFG is total savior. Well done !!! 👍 💯 🥇

**Comment by rtyley** [comment]
Thanks @mitchellkrogza - positive feedback is always much appreciated! You can always donate at https://www.bountysource.com/teams/bfg-repo-cleaner if you'd like to - but in any case, I appreciate you raising such a positive issue. I'm glad you've found that the BFG is fabulous - that's one issue I can live with!

**Comment by mitchellkrogza** [comment]
@rtyley soon as I get some spare $$ in my paypal account I will make a donation for sure. You've done a great job with BFG. Saved my **s for sure.

**Comment by mitchellkrogza** [comment]
@rtyley here's something quite interesting for you. My contributions for the past year were at about 9,200 this morning. After running BFG on this mega repo of mine look what happened to my contributions count. Interesting / bug in their contributions counts ??

![screen shot 2017-09-28 at 3 45 49 pm](https://user-images.githubusercontent.com/9961541/30970178-bcea3126-a464-11e7-9d09-ecc5a8c4bdb1.png)

**Comment by rtyley** [comment]
weird!

**Comment by mitchellkrogza** [comment]
Extremely.
