### ISSUE TITLE
How to deal with iOS framework files?

### ISSUE THREAD

**Issue by blastmann** [rtyley/bfg-repo-cleaner#242]
I use this tool for converting my existed repo to LFS support repo. But it doesn't work when I use cmd below:

`java -jar ./bfg.jar --convert-to-git-lfs '*.framework/**/*' --no-blob-protection`

And the result:

> Cleaning
> --------
> 
> Found 1 commits
> Cleaning commits:       100% (1/1)
> Cleaning commits completed in 54 ms.
> 
> BFG aborting: No refs to update - no dirty commits found??

It seems not working with this pattern matching?

**Comment by javabrett** [comment]
Do you actually need those trailing wildcards?

**Comment by blastmann** [comment]
@javabrett Yes. Because there are different frameworks in my project and iOS frameworks are directory. I have to use git-lfs track those files by using '*.framework/*' at least.
