### ISSUE TITLE
unrelated content in output

### ISSUE THREAD

**Issue by jceaser** [rtyley/bfg-repo-cleaner#243]
```
--
You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up: https://www.rescue.org/topic/refugees-america
--
```

Don't get me wrong, I hate trump, but this kind of text makes me think that I'm introducing hacked code onto my computer. This needs to be removed as the out of place context makes people think their computer has been hacked. The last thing I need to spend an hour in the sysadmin's office explaining why I have this great tool installed on my laptop.

**Comment by dsouzarc** [comment]
Duplicate [Issue](https://github.com/rtyley/bfg-repo-cleaner/issues/210)

**Comment by Jonathonbyrd** [comment]
I hate this kind of bullshit agenda

**Comment by GammaGames** [comment]
I thought it was funny when I saw it ¯\_(ツ)_/¯ Obviously @rtyley isn't going to remove it, but it might be worth it to at least add a flag to disable it in the output.

**Comment by SuborbitalPigeon** [comment]
Trump is an utter disgrace, but I'm not a fan of putting American political messages in something that is used around the world. I personally don't really care.

**Comment by jeffvandyke** [comment]
Seriously, political messages do not belong in technical projects like this, and only sour the usage experience. It's patently unprofessional in any project.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
