### ISSUE TITLE
Political Rhetoric has no place in tooling

### ISSUE THREAD

**Issue by billbr** [rtyley/bfg-repo-cleaner#248]
No matter what your political feelings are, they should not be expressed in tool output.

**Comment by rtyley** [comment]
Why?

**Comment by vandadnptv4** [comment]
I actually have to agree with this. I have never voted for any president, in any of the 4 countries I've lived in but I found that statement to be so out of place I was taken aback by it.

Please leave politics out of this and let us enjoy this great tool for what it is: a tool to ease the lives of developers around the world, and not as a platform to spew out political statements which have neither anything to do with the tool neither with any of its usages or users.

**Comment by billbr** [comment]
vandadnptv4, much more eloquently stated. Thank you. I respect everybody's right to an opinion on whatever part of the world stage is being watched.  You can express it in whatever venue that want to (legal or not). However, I would really hate to see such good work dismissed, banned, or otherwise restricted because of political rhetoric being printed on every execution.

**Comment by batflyer** [comment]
The message was merged in with pull request #198 (rtyley's statement is available here).

Multiple issues have been submitted on this topic (Issue #223 #222 #206 #205), each of these are closed now.

**Comment by javabrett** [comment]
> I respect everybody's right to an opinion on whatever part of the world stage is being watched. You can express it in whatever venue that want to

> For use in my company, we will need to build the tool from source and remove the statements.

This is sufficient to close this issue - complete solution.  License is permissive. Use the source-code within the license and do as you please.

**Comment by banderson** [comment]
I'm _way more_ surprised at the outrage in these github issues than I was to see the message in my console. @rtyley created an outstanding tool and gave it to the community to make our lives easier. 
 I'm fed up with the daily political commentary as much as anyone, but he can express his views here if that's what he thinks is right.

> This is sufficient to close this issue - complete solution. License is permissive. Use the source-code within the license and do as you please.

As @javabrett indicated above, this is open source where we can build what we want, and @rtyley is
 doing just that 👏

**Comment by vandadnptv4** [comment]
> This is sufficient to close this issue - complete solution. License is permissive. Use the source-code within the license and do as you please.

While true, it is very unprofessional but perhaps "@rtyley is doing just that"!

Have a nice day

**Comment by vitgorbunov** [comment]
It's kind of extreme to make fork just to remove a message. You can use simple script wrapper instead

```
#!/bin/bash
java -jar bfg.jar $* | grep -v 'You can\|make people\|give up'
```

**Comment by n4ru** [comment]
Echoing this sentiment. Garbage.

**Comment by jimbo1qaz** [comment]
Missing a few head commits, but same release without message: https://github.com/Tatsh/bfg-repo-cleaner/releases

**Comment by shellscape** [comment]
This issue exactly. I think it's great that the author has a cause and believes firmly, willing to take action on their beliefs and try to make a difference in following them. But forcing that upon anyone in this context is just plain wrong. We're inundated by loud political rhetoric at every turn these days, and I'm woeful and disappointed that someone has taken the opportunity to inject it - without consent or notice - into a download. It is for these same reasons that advertisements are not considered good form for CLI tools. Make a statement in a medium that isn't an ambush. At best you're only speaking to those who already agree with you. If one didn't already agree with you, I would be loathe to see that message, and would leave a sour taste. _At worst you're further alienating and pushing away those who don't agree, and contributing to the extreme polarization we're facing today._ It serves no good, real purpose. It doesn't raise awareness of the intended issue. 

Poor choice all around.

**Comment by tflo** [comment]
Honestly guys, if I didn’t agree with the author’s statement I would seriously consider to not use the software.

It is true that it is not very common to include a political statement with software, and that means that to the author of bfg his statement really is important. You should respect that.

**Comment by shellscape** [comment]
@tflo I'd respect it if it wasn't an ambushed message. If this were a religious message or advertising you can safely bet our peers would be up in arms. There's also something to be said for respect for one's users in the open source community. The author could have shown some more tact in his delivery, could warn people ahead of time before downloading that it contains political messages, or could have simply offered a flag to view the message instead of forcing it on users every run.

Your comment about not using it is moot. We've already moved on, but that doesn't negate the matter that what the author chose to do was in poor form.

**Comment by rtyley** [comment]
I hope these explanations help you understand my position on  including the message in the output of the BFG: https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 &  https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770
