### ISSUE TITLE
help needed : accidentally issued "git push" *before* the 'reflog expire' thing

### ISSUE THREAD

**Issue by mhow2** [rtyley/bfg-repo-cleaner#250]
Hi,
I forgot to issue the 'reflog expire' thing prior to push back the repo.
I can run `git reflog expire --expire=now --all && git gc --prune=now --aggressive` afterwards on my local bare copy but then I am unable to push it again with message `Everything up-to-date`
Now I'm stuck with an online repo that still mention (I guess) the values I have replaced with `-rt`  . What should I do ?
Regards,

**Comment by rtyley** [comment]
This isn't a bug with the BFG, so I'd appreciate it if you didn't open it
as a GitHub issue. You'll find a far wider audience of helpful answerers if
you ask this as a question on stackoverflow.com (use the bfg-repo-cleaner
tag) and the answer will have better visibility for other searchers then
too.

**Comment by mhow2** [comment]
You're totally right and I'm sorry for the inconvenience.
