### ISSUE TITLE
Doubled number of contributions after using

### ISSUE THREAD

**Issue by eshlykov** [rtyley/bfg-repo-cleaner#263]
After cleaning a repo, on profile page the number of some contributions is doubled.

My MWE: [mwe-doubled-contributions](https://github.com/eshlykov/mwe-doubled-contributions).

You can see 3 commits only, but my profile shows 5 commits.
![image](https://user-images.githubusercontent.com/22434445/36196929-502cac4e-1183-11e8-98b4-279eb6898ee0.png)
![image](https://user-images.githubusercontent.com/22434445/36196901-31ef6bfe-1183-11e8-9db1-2bc3939113a3.png)

I suppose that commits which "contain" a removed file (in my example, `LICENSE`), are counted twice after using BFG-Repo-Cleaner.

**Comment by javabrett** [comment]
This looks like an after-effect of how GIthub creates or caches or updates its commit/contribution statistic, perhaps before your repo has a `gc` run on it.  Sure BFG created the rewritten history, but it can't control how Github calculates the stats.

Some views already show the correct commit count of 3.  It would be interesting to see whether Github eventually updates to correct contribution stats.

Not a BFG issue that I can see.

**Comment by eshlykov** [comment]
I've wrote to GitHub Support, and they just rebuilt the contribution data for my account. Also I found out this problem occurs even after hard reset and force push.

So it's definitely not a BFG issue.
