### ISSUE TITLE
Delete files with filenames containing several dots and dashes

### ISSUE THREAD

**Issue by sdespont** [rtyley/bfg-repo-cleaner#277]
Is there any reason why the file "Validation-document-127.0.0.1-1527687974.zip" which I am sure that  is part of the history is not found?

`java -jar bfg-1.13.0.jar --delete-files Validation-document-127.0.0.1-1527687974.zip repo.git`

`BFG aborting: No refs to update - no dirty commits found??`

Is the reason could be the `dash `or `dot `in the filename?

**Comment by javabrett** [comment]
> which I am sure that is part of the history
How have you established that?  Does it still remain in a protected ref (`HEAD` of `master`)?

Case/caps maybe?

This should work fine.

**Comment by sdespont** [comment]
Thank you for your answer. I think you are right, the files are no longer part of the history. The fact is that the files can still be view in BitBucket, but I think it is a cache problem.

**Comment by javabrett** [comment]
Please close this issue.
