### ISSUE TITLE
--strip-blobs-bigger-than also removed other files

### ISSUE THREAD

**Issue by JESii** [rtyley/bfg-repo-cleaner#280]
Created a new copy of my repo with the `--mirror` option. Then I ran bfg [1.13.0] twice on my repo, once to remove blobs > 25M
`java -jar bfg-1.13.0.jar --strip-blobs-bigger-than 25M .dotfiles.git/`
It reported that the following files were removed:
```
 Chromium Embedded Framework
 python-packages-27.zip
```
and then again, when everything looked OK, I ran it again to remove blogs > 5M
`java -jar bfg-1.13.0.jar --strip-blobs-bigger-than 5M .dotfiles.git/`
It reported the following files were removed:
```
cryptography.hazmat.bindings._openssl.so
 icudtl.dat
libdropbox_python.2.7.dylib
```
It all looked good, but when I started a new terminal, I found that:

- my `.bashrc_aliases` file had also been removed
- my .vim configuration was fouled up : couldn't start normally due to `.vimrc` issues and missing plugins 

Any idea what might have happened?

**Comment by javabrett** [comment]
Does anything in stdout or the reports mention anything to do with `.bashrc_aliases`?  I don't suppose you can reproduce this with a minimal shareable repo?

How did you establish `.bashrc_aliases` was removed - cloned the repo?

**Comment by JESii** [comment]
My bad; turns out that file had not been committed, so it got swept out with the trash. Sorry for the false alarm.
