### ISSUE TITLE
syntax error if ')' in filename

### ISSUE THREAD

**Issue by MaxMargolis** [rtyley/bfg-repo-cleaner#282]
I'm trying to delete a file that has parentheses in the filename. I get the following error: 
syntax error near unexpected token `('
Any suggestions?
Thanks!

**Comment by javabrett** [comment]
Which OS/shell are you using, and have you tried escaping that character, as it is usually shell-special?

**Comment by MaxMargolis** [comment]
thanks for your follow up! yeah, I sorted it out with some quotes.
