### ISSUE TITLE
Unrelated message

### ISSUE THREAD

**Issue by denysvitali** [rtyley/bfg-repo-cleaner#296]
![screenshot-2018-10-17_10-40-02](https://user-images.githubusercontent.com/4939519/47073659-0d008580-d1f9-11e8-9661-14fc72550617.png)

This thing was introduced in https://github.com/rtyley/bfg-repo-cleaner/commit/d2713b49aff7fde4d4cf5eba92edea25971ef639.
https://github.com/rtyley/bfg-repo-cleaner/blob/d2713b49aff7fde4d4cf5eba92edea25971ef639/bfg/src/main/scala/com/madgag/git/bfg/cli/stoptrump/package.scala#L1-L29

![Excuse me](https://i.kym-cdn.com/entries/icons/original/000/026/913/excuse.jpg)  
  
I don't really think that politics should be included in software :upside_down_face:

**Comment by rtyley** [comment]
Duplicate - see https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
