### ISSUE TITLE
--delete-files doesn't seem to work

### ISSUE THREAD

**Issue by DigiBee** [rtyley/bfg-repo-cleaner#298]
I am trying to remove some.web.config in our repo using bfg. I tried to remove a static html and and bfg worked and it removed that file from all the commits. The problem is I cannot do it for any .config files in our project. I don't get any errors. Are there any issues removing config files?

**Comment by DigiBee** [comment]
I did a delete for web.config and what I've noticed is the web.config in the root directory was not deleted but the web.config inside a subdirectory got deleted and successfully removed from the GIT history. Is there any reason why that happened?

**Comment by DigiBee** [comment]
This is my command 
`java -jar /d/bfg.jar --delete-files "{web.config,web.debug.config,web.staging.config,web.release.config}" --no-blob-protection`

I've also tried doing a single file deletion command as well

**Comment by javabrett** [comment]
Do you have a shareable repo where this problem can be reproduced? BFG version?

**Comment by DigiBee** [comment]
Unfortunately all repos are private.

**Comment by javabrett** [comment]
Can you construct a trivial public repo which reproduces the problem?

**Comment by DigiBee** [comment]
I've created this public repo
https://github.com/DigiBee/BfgTest.git

I was able to delete a static text file with no issues but I cannot remove the web configs still specifically web.config, web.release.config, web.debug.config

with message "BFG aborting: No refs to update"

**Comment by javabrett** [comment]
Have you tried `Web.config` etc.?

**Comment by DigiBee** [comment]
Yes I tried just web.config, it also doesn't work. I will say the aborting message and even after reflog and gc and push, it's still there.

**Comment by DigiBee** [comment]
Yes I tried. It looks like it's successful but the config file is still there.

**Comment by DigiBee** [comment]
I am not sure but maybe it doesn't work for files that's been part of the first push?

**Comment by javabrett** [comment]
Works fine for me, these files are deleted.  Maybe confirm the OS you are running on, the exact BFG version and the exact command lines you use, starting with cloning the repo.

**Comment by DigiBee** [comment]
I didn't clone the repo as this is just a test copy. I thought it's just optional. I am using windows 10 and I am using the latest version (I just downloaded the jar yesterday)

**Comment by DigiBee** [comment]
java -jar /d/bfg.jar --delete-files web.config --no-blob-protection
git reflog --expire=now && git gc --prune=now --aggressive
git push -f

**Comment by javabrett** [comment]
You keep typing `web.config` even though your repo file has proper case `Web.config`.  Why do you do that?  I mentioned `Web.config` above, have you tried it?

Try using a filesystem with proper case-sensitivity (not Windows), or configure Git to compensate.

Please pay attention to the case of your filenames.

**Comment by DigiBee** [comment]
This is basically a new repo I've committed for testing.
1. I created a new project
2. Created a new repo in github
3. Committed my proj to the new repo
4. ran the delete bfg command and push

**Comment by DigiBee** [comment]
Darn, apologies. I am not really thinking of case sensitivity. That worked. Thanks a lot.

**Comment by javabrett** [comment]
Please close this issue.
