### ISSUE TITLE
Strip large files except for particular filetype/glob

### ISSUE THREAD

**Issue by osdiab** [rtyley/bfg-repo-cleaner#299]
Hi, I'm trying to strip out all the uncompressed images from my website repo, but I don't want to remove relatively large Javascript sourcemaps.

So I run this command:

```bash
bfg --strip-blobs-bigger-than 800K --filter-content-excluding "*.js.map"
```

but it seems like `--filter-content-excluding` only applies to the text replacement functionalities, not to the `--strip-blobs-bigger-than` field.

Is there a way to filter those changes out, either via the tool, or with git commands somehow?

**Comment by javabrett** [comment]
If you find that BFG is unable to express the filtering you need, and you are not able to enhance it to do-so, then the standard workaround is:

- Use scripting outside BFG to predetermine all the blob ids of files you want to delete.  This could be simple or moderately complex depending on exact needs.
- Feed that list to `bfg ... --strip-blobs-with-ids ...`

**Comment by osdiab** [comment]
OK, thanks for the tip! Will close, assume this is wontfix.
