### ISSUE TITLE
Equivalent of git filter-branch --subdirectory-filter

### ISSUE THREAD

**Issue by mloskot** [rtyley/bfg-repo-cleaner#303]
I have been trying to find BFG command and combination of options which is equivalent to `--subdirectory-filter`, for example:

```
git filter-branch --prune-empty --subdirectory-filter vendor/
```

There is similar question on StackOverflow, [Moving git history of a directory from repository A to repository B](https://stackoverflow.com/q/52183721/151641), unfortunately without any answer.

There are also BFG issues which I'd connect to my question:

- #183, Command removing all files except, seems directly related, but the answer it received suggests the OP has been misunderstood or the question badly expressed.

- #12, Ability to remove directories, which seems to suggest there is no such feature as `--subdirectory-filter` available and some possibilities are discussed

However, the findings seem inconclusive to me, so I decided to ask question with hope to clarify the issue.

**Comment by javabrett** [comment]
There is no such feature in BFG - you would have to add one yourself if you needed this.

The main barrier is - the way BFG currently works, it is unconcerned with specific _paths_ of blobs in the repo.  It just visits all commits, then recursively processes each commit's trees and subtrees.  As it does so it does not keep any track of the "directory" position of the current subtree it is processing, so there's no support for any features which work with full paths.

**Comment by mloskot** [comment]
Thanks for clarifying that.
