### ISSUE TITLE
Repo-management software shouldn't be political

### ISSUE THREAD

**Issue by hamx0r** [rtyley/bfg-repo-cleaner#306]
I love this tool - first time user.  Bummed to see that I have to get political messages in git projects.  I know it's not my project so you can obviously do whatever you want, but it sure would be cool to keep a corner of our lives free of politics since it's so divisive...afterall, open source requires many different kinds of people _coming together_ to support something great, like this project!   Division is easy.  Unity is hard.  I'll make a PR.

**Comment by Bak3y** [comment]
Especially given the guy who made the commit @rtyley lives in the UK, so he doesn't have a dog in the fight.  Useless cruft in the code.

**Comment by jeshan** [comment]
> I'll make a PR
@hamx0r Don't bother:
![image](https://user-images.githubusercontent.com/1020565/53701092-f60ea880-3e12-11e9-9cc8-18b74abc4a34.png)

@Bak3y Check out the forks, e.g 
https://github.com/Tatsh/bfg-repo-cleaner/releases/tag/v1.12.15-no-agenda

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
