### ISSUE TITLE
Remove political views

### ISSUE THREAD

**Issue by RafaGago** [rtyley/bfg-repo-cleaner#313]
Think how nasty would be to use the CLI if every tool would push its political views on its output.

**Comment by talkquazi** [comment]
You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up: https://www.aclu.org/

^ This makes your software political and you should never involve politics in your code @rtyley

**Comment by racinmat** [comment]
I propose optional flag that would print out political statements, but by default, it should not.
For example, flag `--woke` would be working, so running `bfg --woke` would print political statement to the stdout.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
