### ISSUE TITLE
Avoid political propaganda

### ISSUE THREAD

**Issue by j0hnwhyte** [rtyley/bfg-repo-cleaner#317]
There is a political message in the program log.

This is a tool for coding applications, not doing political propaganda. While I may or may not agree on the contents of the message, it's totally unneeded and not professional to include it.

You're targeting the wrong people if you want to make propaganda, and in the wrong way.

**Comment by j0hnwhyte** [comment]
Plus, before writing "this is a dupe.. duh!" please keep the current issue's discussion open and make plans to correct this blunder

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
