### ISSUE TITLE
This is not the kind of "opinionated" I was expecting

### ISSUE THREAD

**Issue by brendan-rius** [rtyley/bfg-repo-cleaner#318]
Getting this message when using your tool:

```
--  
You can rewrite history in Git - don't let Trump do it for real!  
Trump's administration has lied consistently, to make people give up on ever  
being told the truth. Don't give up: https://github.com/bkeepers/stop-trump  
--  
```

As many other people said it, not everyone is American, not everyone cares about politics, or your political agenda.

Is there any plan to remove it?

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
