### ISSUE TITLE
Don't stigmatize substance use disorders in your docs

### ISSUE THREAD

**Issue by drmattyg** [rtyley/bfg-repo-cleaner#320]
Please accept this suggestion in the spirit of positive, progressive feedback:
"The BFG treats you like a reformed alcoholic: you’ve made some mistakes in the past, but now you’ve cleaned up your act."  Lots of reasons why this is not a good idea in public-facing documentation:
- Your users may have faced a substance use disorder in the past.  This kind of comment trivializes their disorder and their experience, which can be hurtful and traumatizing.  Imagine if this was a joke about being a sexual assault survivor, instead of a survivor of an alcohol use disorder.
- The term "alcoholic" is being deprecated by clinicians who are moving toward a harm-reduction treatment modality for substance use disorders.  "Alcoholic" is an identity; it implies that the problem is inborn to the individual.  In fact, alcohol use disorder is a disease, and it is treatable.  This is a differentiator between current evidence-based practices for treating SUDs and older modalities like AA, which are not based on scientific evidence.  The term "alcoholic" is much more common to AA and other twelve-step approaches, which are faith-based and not evidence-based.

Thanks

**Comment by rtyley** [comment]
Thank you, those are clear points and I appreciate you laying them out for me. I can't offer any sufficient justification for my use of "reformed alcoholic" - I'll fix the documentation later today.

**Comment by mbomb007** [comment]
So you care about not offending people who have struggled with alcohol but not people who support the president? Seems legit.

**Comment by mereswine** [comment]
@mbomb007 it sounds like you would prefer for people who support Trump to be classified the same way as people with a real disease. Can't say I disagree....
