### ISSUE TITLE
Don't politicize a project

### ISSUE THREAD

**Issue by mbomb007** [rtyley/bfg-repo-cleaner#324]
Your political agenda is not welcome in this project. Women die all over the world because they are aborted as babies. Half of your users disagree with your views, so it's important that you understand that. If you think Trump is the only liar, just look at all the lying done by the Democratic party. It's politics, and it happens on both sides.

Please remove your biased views from your project from being printed all the time:

> You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up

Until they are, I think it's reasonable to expect this issue to keep showing in your queue. Especially since Democrats tend to rewrite history more, trying to take Christianity out of America's history. Your view is extremely biased.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
