### ISSUE TITLE
Trump administration message

### ISSUE THREAD

**Issue by onknows** [rtyley/bfg-repo-cleaner#325]
Trump lied consistently?

And Obama didn't? Hitlary would have been a better choice? Because she doesn't lie? 

America is not a democracy and does not have rule of law. No president is going to change that. America is a vassal state.

**Comment by westonganger** [comment]
Please remove the political propaganda. The last thing we need these days is someone else trying to tell us how we should think. 

This is a personal conclusion that people need to make on their own. Not have it shoved down their throats when they are not looking.

**Comment by jamesbrooks** [comment]
I was pretty disgusted today to see this today when I ran bfg. Whether or not I agree with the message *my* terminal is not the place to broadcast political messages!

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
