### ISSUE TITLE
This project is hypocritical

### ISSUE THREAD

**Issue by abaga129** [rtyley/bfg-repo-cleaner#328]
I just want to say that the way this project is handled is very hypocritical.  It is ran as a dictatorship rather than a democracy.  The recent PR #198 was not asked for and certainly not wanted by the majority of users, yet is was merged.  Now when anyone tries to speak out against this, the issue/PR is closed without discussion.  The message is about a certain political candidate erasing history and lying about the truth, but is it that much different than hiding the truth (which is what is happening every time someone voices concerns about this).

To the author:
Please consider removing the political messaged added in #198, or at least hear your users out.  I really like this tool, but I can no longer recommend it to anyone, and will likely have to find an alternative.  Not everyone shares the same view.  Developers come from all walks of life.  These types of opinions shouldn't be shoved down their throats every time they want to use this tool.

I strongly urge you to consider removing the message.  The only thing it will do is anger people.  Whether someone agrees with it or not, most of us don't want to see something like that in our terminals while working on our own projects.

I truly love open source software and it concerns me to see something like this.  OS is about collaboration with people from many backgrounds.  It shouldn't be a tool to push someone's political agenda.

Again please consider leaving this open for discussion at least.
Thanks.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.

Pick your battles man. Of all the causes to fight for, find something better than defending a racist rapist.
