### ISSUE TITLE
Why alienate 50% of America?

### ISSUE THREAD

**Issue by DaniloNovakovic** [rtyley/bfg-repo-cleaner#329]
In Human-Computer Interaction class we learned how we should make software to be usable for large amount of audience (disabled, old, kids etc) in order for it to be successful. 
And then i see Political propaganda in something so cool.... **WHY?**
You basically alienated 50% of American population and possibly even more. 

Do you not see how bad it is from business perspective?

Heck, i don't even care about American politics, i don't care about politics at all! I'm SICK of it!
Programming is place where i am in my own magical little world where everything is possible, and the LAST thing that i want to see is some political agenda messages being thrown at me whenever i run a command!

The only thing that you are gonna change with this is the amount of people using your software and nothing else, which is honestly a shame because you made something really useful and good. Just get rid of that message.

If you wanna share your political opinions do it through other means (make website, hold speeches, etc.) don't do it like this...

Wrote this with my best intentions, don't wanna start debate, just giving my opinion here.

**Comment by tflo** [comment]
Could all you Trump followers, racists, fascists – or what ever you are or define yourselves – _please_ refrain from polluting the Issues with your attempts to tell the author what he has to do?!

If you don’t agree with the author’s message, just stop using this software.

I have subscribed to the Issues to keep me up to date about issues with the BFG scripts, and not to read any right-wing ideological statements.

Thanks.

– Tom

**Comment by DaniloNovakovic** [comment]
@tflo Mate, you completely missed my point. I am NOT Trump follower, i am NOT Clinton follower, i am NOT AMERICAN! My country has been BOMBED by America while we are at it. My country has been RUINED by politics! Brother turned against a brother! Half of my family doesn't speak to me because i am from Serbia! I am SICK of it!

"Racist, fascist" are the ones that did genocide to my people. My grandfather was a war hero in WW2 while we are at it!

"_I have subscribed to the Issues to keep me up to date about issues with the BFG scripts, and not to read any right-wing ideological statements_." -  EXACTLY!

My whole point of this issue is that i ALSO do not want to read any right-wing ideological statements, but i do not want to read any left-wing ideological statement either, and most of people do not want it too!

And again as a summary since you seem to miss my point:
There are 3 types of people:
 1. Left wing - they will be like "oh nice message" 
 1. Right wing - they will probably get angry and just stop using your software
 1. People who are sick of politics (ex. me) - they will get annoyed, come over here on github, and try to argue with you to remove message not because they are offended but because they are ANNOYED with politics!

So out of 3 types of people 2 would probably stop using your software. Now keep in mind that *MOST OF THE WORLD IS NOT AMERICA*, so most of the world would fall into 3rd category.

So what is the result of this political propaganda? Loss of the amount of users using this app, and nothing else! It is less effective then those petitions on petition.org.

Wouldn't it be better approach to just simply remove message, and then step out and TALK upfront, hold conferences for these subject as the creator of great app that EVERYBODY uses (right, left, and others)

**Comment by DaniloNovakovic** [comment]
Another option would be to simply change message to instead of directly attacking Trump, or any other person that you do not like,  to simply say "To support this project you can join us at _LINK_ where we discuss various topics such as  _TOPIC_".

Problem solved. Nobody is offended and now you got people interested in clicking the link (even the ones that do not agree with you which is important if you wanna change their opinion).

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
