### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by nathanieltagg** [rtyley/bfg-repo-cleaner#33]
Trying to run the installer does nothing on my computer.

Mac OSX Mavericks 10.9, just updated by JRE:
$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

Double-clicking on the file seems to have little effect. If I try to run from the command line:
$ java -cp . bfg-1.11.1.jar
Error: Could not find or load main class bfg-1.11.1.jar

I tried downloading the source, but I have no idea what build system this thing uses.

**Comment by reggi** [comment]
* Do you have to rename bfg.jar file? 
* Where is the bfg.jar file supposed to live? Are you supposed to drop it into your project?

**Comment by reggi** [comment]
I'm getting `Unable to access jarfile bfg.jar` and it's very frustrating.

**Comment by reggi** [comment]
`sudo java -jar /Users/thomas/Desktop/project/bfg.jar --replace-text /Users/thomas/Desktop/project/banned.txt /Users/thomas/Desktop/project/.git`

**Comment by rtyley** [comment]
Sorry to hear about your difficulty getting the BFG running - I'm glad you got it working! Ideally, I don't think you need the `sudo` tho'.

If you're a Mac user and a little unfamilar with how to run Java, you could use [Homebrew](http://brew.sh/) to [install the BFG](http://brewformulas.org/Bfg), which would let you run it like this:

```
$ bfg --replace-text Desktop/project/banned.txt Desktop/project/.git`
```

I'm not personally responsible for the Homebrew package of the BFG, but do update it from time to time.

**Comment by reggi** [comment]
This works brilliantly `brew install bfg` :)

**Comment by v3nt** [comment]
i too get 'Unable to access jarfile bfg.jar'  after running 'brew install big'.

Any ideas one what is going wrong? 

OS X
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

**Comment by javabrett** [comment]
Not sure that this addresses your problem @v3nt , but note that per https://rtyley.github.io/bfg-repo-cleaner/ 

> The Java Runtime Environment (Java 7 or above - BFG v1.12.3 was the last version to support Java 6)

... so you will at least need to fix that default JDK, run v7 minimum if you want to run the latest BFG.

**Comment by liz1027** [comment]
I installed Homebrew, then BFG and still having the message in Terminal Error: Unable to access jarfile bfg.jar, Any ideas

**Comment by javabrett** [comment]
Is `bfg.jar` in the directory you are running in? If not, provide the full path to it.

**Comment by liz1027** [comment]
I seem to. Have fixed the error, 

Thanks
Liz
