### ISSUE TITLE
it doenst work

### ISSUE THREAD

**Issue by johnmarinelli** [rtyley/bfg-repo-cleaner#330]

**Comment by johnmarinelli** [comment]
idk y.  it just breaks

**Comment by vineeshvs** [comment]
Did you get it to work? If not, could you post the steps which you have followed.

You could refer to https://github.com/rtyley/bfg-repo-cleaner/issues/333

**Comment by whalemare** [comment]
+1. Not delete files, just broke repo

**Comment by aakoch** [comment]
Please include the steps you did so we can help troubleshoot your issue. Just saying "it doesn't work" doesn't help.
