### ISSUE TITLE
Repo size reduced locally but Bitbucket shows increased repo size.

### ISSUE THREAD

**Issue by vineeshvs** [rtyley/bfg-repo-cleaner#333]
I have done the following and the new size of the repo (as per git count-objects -vH) is 134 MB. The commits are updated in Bitbucket but the size is not reduced (from the oriignal 1.27GB).Instead the repo size has become 1.4 GB now (increased)! What could be the reason?

1. git clone --mirror https://username@bitbucket.org/repo-name
2. Created a backup of the mirrored clone.
3. Downloaded bfg-1.13.0.jar alongside the cloned mirror from https://rtyley.github.io/bfg-repo-cleaner/
4. java -jar bfg-1.13.0.jar --strip-blobs-bigger-than 100M repo-name.git/
5. cd repo-name.git
6. git reflog expire --expire=now --all && git gc --prune=now --aggressive
7. Verified the repo size reduction (git count-objects -vH).
8. git push

**Comment by vineeshvs** [comment]
Mail support@bitbucket.org and ask them to do a `git gc`

Ref: https://stackoverflow.com/questions/49903193/bfg-repo-cleaner-tool-successful-but-repo-size-not-decreased/57848454#57848454

**Comment by ndvbd** [comment]
The only way is by email?
