### ISSUE TITLE
Feature request - closed PRs are not scrubbed by BFG

### ISSUE THREAD

**Issue by RecodeL** [rtyley/bfg-repo-cleaner#345]
Hello,

Is it possible to add a feature that would scrub the sensitive data in closed PRs? Thanks

**Comment by aakoch** [comment]
This sounds like a feature of Bitbucket or Github, not of Git. AFAIK, Git doesn't have the concept of pull requests.

**Comment by javabrett** [comment]
@RecodeL in most managed Git platforms, the (hidden) refs owned by PRs etc. are read-only.  That is why many folks have trouble shrinking their hosted repos, despite BFG being able to shrink them locally in a clone quite easily.

**Comment by RecodeL** [comment]
Thanks folks! I'll close it for now.
