### ISSUE TITLE
Useless and unprofessional political statement

### ISSUE THREAD

**Issue by youngde811** [rtyley/bfg-repo-cleaner#347]
I know this is a duplicate, but perhaps you could add a command-line flag to suppress your political statement in the BFG output. You have every right to state your opinion, but that kind of stuff is unprofessional in a work environment. Yup, we don't have to use your software, but it's very good and a shame to reject it just because of this issue. Our chief architect, and project managers in general, would reject your work out-of-hand due to your poor choice.

I've written a bash script that wraps the BFG functionality, adds some additional git maintenance commands, and runs the BFG output through sed to filter out the anti-Trump nonsense.

**Comment by adamgiesinger** [comment]
Oh no!
Someone made a tool that you use for *free* and you complain about a console message he adds?
The author put his free time into this project and you have nothing better to do than be mad about some outputs he puts into his project?
At least he isn't lying, unlike Trump.

**Comment by youngde811** [comment]
Try not to be a dick, man. I don't give a shit about the author's political views. I DO care about professionalism though.

**Comment by youngde811** [comment]
Oh, and Adam. I've run two open source projects for over a decade. My free time and effort. Both are used to this day. Regardless of my personal beliefs, my software is professional. That's how it should be. Fool.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
