### ISSUE TITLE
what is BFG?

### ISSUE THREAD

**Issue by LeiYangGH** [rtyley/bfg-repo-cleaner#348]
abbreviation for what?

**Comment by rtyley** [comment]
1. It's a friendly tool, just like the friendly giant from The BFG by Roald Dahl. The CLI arguments were designed to be as simple as possible and match up to user's needs.
2. It's a very *destructive* tool, just like the BFG 9000 in the classic computer game 'Doom - (a Big Fucking Gun that obliterates stuff)
3. It's the letters of 'git filter-branch' reversed! 'git filter-branch' was the only tool to rewrite history before I created the BFG - it was *slow* on big repos, and very tricky to use correctly. I was deliberately trying to make a new tool that was the exact opposite.

**Comment by LeiYangGH** [comment]
thanks for your detailed explanations.
