### ISSUE TITLE
Dead link on the JAR download button

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [rtyley/bfg-repo-cleaner#352]
`https://repo1.maven.org/maven2/com/madgag/bfg/LATEST/bfg-LATEST.jar` is a dead link; any other way to download the JAR? Thanks.

**Comment by rtyley** [comment]
Thanks for reporting this @FredericoCoelhoNunes , I've fixed the broken links on the site with 20752c7d1a4005a1c0de4ed8bfb1e1d7d603d0bb - you can download the latest version of the BFG from:

https://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar

...thanks again for the report!
