### ISSUE TITLE
Remote refs appear to have been corrupted after running BFG

### ISSUE THREAD

**Issue by jlevers** [rtyley/bfg-repo-cleaner#356]
First of all, thank you for creating (and open sourcing) this awesome tool!

I successfully removed a number of large objects from my repository with `java -jar bfg.jar --delete-files \*.obj path/to/repo`. I then realized that I wanted to remove them from the `HEAD` of `master`, so I ran the command again with `--no-blob-protection`.

Afterwards, `git reflog expire --expire=now --all` ran with no output, but when I run `git gc --prune=now --aggressive`, it fails with the following error message:

```
error: refs/remotes/origin/master does not point to a valid object!
error: refs/remotes/origin/restructure does not point to a valid object!
error: refs/remotes/origin/HEAD does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/remotes/origin/restructure does not point to a valid object!
fatal: bad object refs/remotes/origin/HEAD
error: failed to run repack
```

I get similar messages when I try to run basically any other Git-related command in the repo. Any idea what happened here?

Thank you!

**Comment by javabrett** [comment]
Did you clone into a bare repo?

**Comment by jlevers** [comment]
It was a regular repository that I attempted to convert to a bare one like so:
```bash
```
 by removing the working files, copying the contents of `.git/` into the main directory, and running

**Comment by jlevers** [comment]
It was a full repo that I attempted to turn into a bare one like so:

```bash
$ cp repo/.git repo.git
$ git config --bool core.bare true
```

I can't re-clone the remote repo as a bare repo, for a variety of reasons. Although, now that I'm typing this, I realize there's probably a way to clone a local repo into a bare repo. I'm going to look into that now.

**Comment by javabrett** [comment]
`git clone --bare` is definitely the way to go.

**Comment by jlevers** [comment]
Yep, rerunning everything after doing `git clone -l --bare path/to/local/repo` fixed it. My bad, thank you @javabrett.
