### ISSUE TITLE
Branches deleted

### ISSUE THREAD

**Issue by adamski** [rtyley/bfg-repo-cleaner#358]
I ran the tool on a mirror of my repo, to delete instances of a given filename. 
All looked good from inspecting the affected and new commits. 
I then ran (as per instructions) 
```
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

and pushed to my git server with `git push origin master` (out of habit..)
I then saw that all branches apart from `master` are gone!

Did I do something wrong? 

Luckily I still have the original repo state on my hard drive...

**Comment by javabrett** [comment]
Unclear what might have happened. Restore from your good backup?

**Comment by adamski** [comment]
I think the `git push origin master` may have caused it. Anyhow, I did restore, and tried again and it worked beautifully. Thanks for this tool!
