### ISSUE TITLE
Remove political propoganda from developmental projects

### ISSUE THREAD

**Issue by vikrambharadwaj** [rtyley/bfg-repo-cleaner#360]
Please remove political propoganda from developmental projects, You must restrict such political views in your personal space. 

$ git log bfg/src/main/scala/com/madgag/git/bfg/cli/stoptrump/package.scala
commit d2713b49aff7fde4d4cf5eba92edea25971ef639 (origin/trump-message)
Author: Roberto Tyley <roberto.tyley@gmail.com>
Date:   Thu Feb 2 14:26:19 2017 +0000

    Encourage people to not give up in the face of Trump

    This doesn't relate to the functionality of the BFG, and some might find
    the message unwanted. Yet Trump and his administration are a massive
    threat to the future of humanity, and they have the power to repeat their
    lies, hate and bile - loudly and incessantly. Occasional reminders that
    they're full of shit are a good thing.

**Comment by vikrambharadwaj** [comment]
BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive


--
You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up: https://www.aclu.org/
--

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
