### ISSUE TITLE
Please remove political messages

### ISSUE THREAD

**Issue by demisx** [rtyley/bfg-repo-cleaner#363]
Please remove political messages. There is enough brain washing going on from our fake news CNN, ABC, CBS, MSLCD and such. Or at least consider `s/Trump/Schiff/g`.

You have a good product -- keep it this way.

**Comment by knakamura13** [comment]
It's not brainwashing if it's promoting anti-corruption...

**Comment by demisx** [comment]
@knakamura13 Yeah. 3  years of investigation,  500 witness, more than 2,800 subpoenas turn up nothing, no charges. Obviously, you have information that no one else does. 

Corruption doesn't yield this:
- Almost 4 million jobs created since election.
- More Americans are now employed than ever recorded before in our history.
- Created more than 400,000 manufacturing jobs since my election.
- Manufacturing jobs growing at the fastest rate in more than THREE DECADES.
- Economic growth last quarter hit 4.2 percent.
- New unemployment claims recently hit a 49-year low.
- Median household income has hit highest level ever recorded.
- African-American unemployment has recently achieved the lowest rate ever recorded.
- Hispanic-American unemployment is at the lowest rate ever recorded.
- Asian-American unemployment recently achieved the lowest rate ever recorded.
- Women’s unemployment recently reached the lowest rate in 65 years.
- Youth unemployment has recently hit the lowest rate in nearly half a century.
- Lowest unemployment rate ever recorded for Americans without a high school diploma.
- Under my Administration, veterans’ unemployment recently reached its lowest rate in nearly 20 years.
- Almost 3.9 million Americans have been lifted off food stamps since the election.
- The Pledge to America’s Workers has resulted in employers committing to train more than 4 million Americans. 
- 95 percent of U.S. manufacturers are optimistic about the future—the highest ever.
- Retail sales surged last month, up another 6 percent over last year.
- Signed the biggest package of tax cuts and reforms in history. After tax cuts, over $300 billion poured back in to the U.S. in the first quarter alone.
- As a result of our tax bill, small businesses will have the lowest top marginal tax rate in more than 80 years.
- Helped win U.S. bid for the 2028 Summer Olympics in Los Angeles.
- Helped win U.S.-Mexico-Canada’s united bid for 2026 World Cup.
- Opened ANWR and approved Keystone XL and Dakota Access Pipelines.
- Record number of regulations eliminated.
- Enacted regulatory relief for community banks and credit unions.
- Obamacare individual mandate penalty GONE.
- My Administration is providing more affordable healthcare options for Americans through association health plans and short-term duration plans.
- Last month, the FDA approved more affordable generic drugs than ever before in history. And thanks to our efforts, many drug companies are freezing or reversing planned price increases.
- Reformed the Medicare program to stop hospitals from overcharging low-income seniors on their drugs—saving seniors hundreds of millions of dollars this year alone.
- Signed Right-To-Try legislation.
- Secured $6 billion in NEW funding to fight the opioid epidemic.
- Reduced high-dose opioid prescriptions by 16 percent during my first year in office.
- Signed VA Choice Act and VA Accountability Act, expanded VA telehealth services, walk-in-clinics, and same-day urgent primary and mental health care.
- Increased our coal exports by 60 percent; U.S. oil production recently reached all-time high.
- United States is a net natural gas exporter for the first time since 1957.
- Withdrew the United States from the job-killing Paris Climate Accord.
- Cancelled the illegal, anti-coal, so-called Clean Power Plan.
- Secured record $700 billion in military funding; $716 billion next year.
- NATO allies are spending $69 billion more on defense since 2016.
- Process has begun to make the Space Force the 6th branch of the Armed Forces.
- Confirmed more circuit court judges than any other new administration.
- Confirmed Supreme Court Justice Neil Gorsuch and nominated Judge Brett Kavanaugh.
- Withdrew from the horrible, one-sided Iran Deal.
- Moved U.S. Embassy to Jerusalem.
- Protecting Americans from terrorists with the Travel Ban, upheld by Supreme Court.
- Issued Executive Order to keep open Guantanamo Bay.
- Concluded a historic U.S.-Mexico Trade Deal to replace NAFTA. And negotiations with Canada are underway as we speak.
- Reached a breakthrough agreement with the E.U. to increase U.S. exports.
- Imposed tariffs on foreign steel and aluminum to protect our national security.
- Imposed tariffs on China in response to China’s forced technology transfer, intellectual property theft, and their chronically abusive trade practices.
- Net exports are on track to increase by $59 billion this year.
- Improved vetting and screening for refugees, and switched focus to overseas resettlement.
- Begun BUILDING THE WALL. Republicans want STRONG BORDERS and NO CRIME. Democrats want OPEN BORDERS which equals MASSIVE CRIME.

**Comment by knakamura13** [comment]
Nice copy paste. Thanks for the good laugh!

**Comment by demisx** [comment]
@knakamura13 Enjoy, my liberal friend. Not something you'd hear on your Fake News networks.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
