### ISSUE TITLE
Remove politcal messaging from the software

### ISSUE THREAD

**Issue by ScottEnock** [rtyley/bfg-repo-cleaner#365]
Just raising the issue as I was surprised when I came across the following message after running the tool:

> You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up being told the truth. Don't give up: 
[link to a political website asking for money]

Whatever your persuasion, I think we can all agree, politics should be left out of the tech space.

It is really unprofessional.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
