### ISSUE TITLE
Why are politics (re Trump) output to console? 

### ISSUE THREAD

**Issue by jtheletter** [rtyley/bfg-repo-cleaner#387]
First-time user of this code. I see several closed issues about this. Why were they closed, this is still a problem. It's useless, distracting, an inappropriate. Example output follows. 

```
You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up: https://www.rescue.org/topic/refugees-america
```

**Comment by youngde811** [comment]
The author doesn't care. I wrote a Bash script that runs the tool's output through sed and filters out the political rubbish. I opened a bug report on this, as have others, to no avail. These reports simply get closed.
 
Yeah, it's unprofessional. I'm going to fork this project and get rid of that crap. Stay tuned. 

Cheers David

**Comment by youngde811** [comment]
I've forked this project, and will have a release soon. Been wanting to learn Scala, now I've a reason 😁.

**Comment by youngde811** [comment]
FYI, for those interested I've forked this project and renamed it 'gitclean'. Anything unprofessional will be removed, and I'll take bug reports and enhancement requests. I should have the first version ready sometime next week. Monitor the project page -https://github.com/youngde811/gitclean - for announcements. I'll make no further posts here. The author of bfg-repo-cleaner does deserve credit for a fine tool, regardless.

**Comment by ymartin59** [comment]
@youngde811 You may also review PRs already included at https://github.com/SeekingMeaning/bfg-repo-cleaner

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
