### ISSUE TITLE
Delete political rhetoric from source code.

### ISSUE THREAD

**Issue by dairennlombard-cbsi** [rtyley/bfg-repo-cleaner#399]
Hello.

We found this inappropriate message in the output of this computer software.

--
You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up: https://www.theguardian.com/us-news/trump-administration
--

It would be a good idea to delete this and any messages like this.

**Comment by Lin-Buo-Ren** [comment]
No, that's not a good idea.  It is the author's freedom of expression to put whatever political message in any software they wrote if they see fit.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770.
