### ISSUE TITLE
Political spam

### ISSUE THREAD

**Issue by funct7** [rtyley/bfg-repo-cleaner#401]
I know there are duplicate issues.
You can spam people all you want. Also, people can bother you all they want because they don't like it.

**Comment by sgrayban** [comment]
LEAVE POLITICS AT HOME NOT IN CODE....

**Comment by TensorTom** [comment]
<img src="https://i.imgur.com/cAyOqKX.png">

One of the most ridiculous things I've ever seen in my terminal. You're not going to bring anyone to your (And I use this term loosely) "cause" doing this. Leave partisan politics out of code please. It's serving no purpose other than to unnerve those who disagree with you.

**Comment by oganm** [comment]
Yep github nonchalantly continues to works with ICE instead. Github is a company whose only motive is to profit. An individual developer has no obligation to keep their opinions out of their work. Stop pestering the guy. He made his position clear. Go use a fork.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770. If you believe that code, science, engineering etc should be kept separate from politics, please do remember that software is written by real live breathing _people_ who live in the real world and may not have the luxury of ignoring politics. Here are some examples where this is viscerally true:

- https://twitter.com/WebDevLaw/status/957256426392494080
- https://www.scientificamerican.com/article/scientific-american-endorses-joe-biden1/
