### ISSUE TITLE
Political spam

### ISSUE THREAD

**Issue by funct7** [rtyley/bfg-repo-cleaner#404]
I know there are duplicate issues.
You can spam people all you want. Also, people can bother you all they want because they don't like it.

(BTW this is how people feel.)

**Comment by funct7** [comment]
I would have left you alone if there wasn't a sanctimonious speech. People who know and understand much better than you don't act sanctimoniously.

**Comment by oganm** [comment]
Do you ever listen to yourself mate... You can't unilaterally declare how you feel as "how people feel" and your speech as "sanctimonious". You're just a guy on the internet trying to silence an opinion you don't like. Don't pretend to have a moral high ground

**Comment by funct7** [comment]
@oganm 
1. I can if there are others also raising the same issue. 
2. I never pretended to have a moral high ground. You see things that aren't there.
3. All I'm saying is there's a time and place for everything. I have a good reason to believe you don't like evangelizing Christians. Guess why people don't like them. People don't like it because they do it out of place. Obviously you can't even tell the difference between silencing an opinion and telling people to put things where they belong.
> your speech as "sanctimonious". 
4. What?

**Comment by funct7** [comment]
> If you believe that code, science, engineering etc should be kept separate from politics, please do remember that software is written by real live breathing people who live in the real world and may not have the luxury of ignoring politics.

A good example of not knowing the right place and time. I suggest you end every meeting at work with a speech about BLM. You'll have people hating BLM in no time.

**Comment by oganm** [comment]
> I suggest you end every meeting at work with a speech about BLM. You'll have people hating BLM in no time

In the end, Carthage was destroyed. The entire point of protest speech is to take things out of their expected place and time. Now unless you consider this a protest as well, continually pestering someone about a previously closed issue is just harassment. And when I don't like you because of this, it won't be because you moved protest speech into Github issues, it will be because I don't like your opinions. Just like I how I don't like evangelizing Christians because I don't like their opinions.

**Comment by rtyley** [comment]
This is a duplicate issue - see https://github.com/rtyley/bfg-repo-cleaner/pull/198#issuecomment-286301000 and https://github.com/rtyley/bfg-repo-cleaner/issues/205#issuecomment-285049770. If you believe that code, science, engineering etc should be kept separate from politics, please do remember that software is written by real live breathing _people_ who live in the real world and may not have the luxury of ignoring politics. Here are some examples where this is viscerally true:

- https://twitter.com/WebDevLaw/status/957256426392494080
- https://www.scientificamerican.com/article/scientific-american-endorses-joe-biden1/
