### ISSUE TITLE
Remove irrelevant American politics

### ISSUE THREAD

**Issue by Unknown6656** [rtyley/bfg-repo-cleaner#414]
> You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, trying to make people give up on ever
being told the truth. Don't give up: https://www.rescue.org/topic/refugees-america

Please do remove this message, as it concerns American _**domestic**_ politics and is not relevant to the rest of the world.
It is further irrelevant, as Mr. Biden has been elected as American President.

**Comment by Unknown6656** [comment]
I just saw that the repository's owner works at the British news outlet "The Guardian".
Considering the outlet's political stance, I doubt that this message will ever be removed.

**Comment by LaoshuBaby** [comment]
**Let code only code please, we don't care about who is president.**

**Comment by Atlas48** [comment]
Fixed in #420.
