### ISSUE TITLE
Deleted File Still There (using old SHA)

### ISSUE THREAD

**Issue by je-hal** [rtyley/bfg-repo-cleaner#466]
I tried out BFG. Our use case is that we want to delete files that were pushed to github.com by mistake. Our files have unique filenames, so basically it works: BFG rewrites git's history and it's gone.

However, I came across an interesting detail: When you still know the old SHA before the history was rewritten, you can still see the old commit and the old file contents, for example using such a link:

```
https://github.com/<org>/<repo>/blob/<old SHA>/<path>/<deleted file>
```

Of course, these commits are 'free floating' now, they don't belong to and branch or repository, but they are still there.

Do you know if there is some kind of garbage collection on github.com that would remove such commits at some point?

Thanks

**Comment by nickpagz** [comment]
@je-hal I've experienced the same issue. According to Github, you need to contact them to have the commit removed. Ref:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#fully-removing-the-data-from-github
