### ISSUE TITLE
bfg just outputs usage instructions

### ISSUE THREAD

**Issue by ostrolucky** [rtyley/bfg-repo-cleaner#48]
I have no idea how am I supposed to use this tool, since all it does is output usage instructions without specifying what parameters are wrong.

```
$ ls -la
total 272
drwxr-xr-x  9 gadelat gadelat   4096 Jun 12 23:46 .
drwxr-xr-x 10 gadelat gadelat   4096 Jun 12 23:42 ..
drwxr-xr-x  8 gadelat gadelat   4096 Jun 12 23:10 .git
-rw-r--r--  1 gadelat gadelat    572 Apr 23 12:29 ubytko.sublime-project
-rw-r--r--  1 gadelat gadelat  51193 Jun 12 22:38 ubytko.sublime-workspace
...
```

<repo> is optional, right?

```
$ bfg --delete-files ubytko.sublime-*
bfg 1.11.2
Usage: bfg [options] [<repo>]
...
```

Okay maybe it's not

```
$ bfg --delete-files ubytko.sublime-* .git
bfg 1.11.2
Usage: bfg [options] [<repo>]
...
```

Maybe it needs to be executed in git's server folder?

```
$ cd /home/git/
$ ls
ubytko.git
$ bfg --delete-files ubytko.sublime-* ubytko.git
bfg 1.11.2
Usage: bfg [options] [<repo>]
...
```

Maybe it needs quotes for glob?

```
$ bfg --delete-files 'ubytko.sublime-*' .git
bfg 1.11.2
Usage: bfg [options] [<repo>]
...
```

Just some examples, nothing works.

**Comment by varunagrawal** [comment]
I am facing this issue on Ubuntu currently. BFG v1.12.12.
Any suggestions?

**Comment by javabrett** [comment]
@varunagrawal how are you launching?

**Comment by varunagrawal** [comment]
The jar is in my home folder. Running: `java -jar ~/bfg-1.12.12 -b 100M repo.git`

**Comment by javabrett** [comment]
Curious about missing `.jar` suffix on your path. Does `repo.git` exist in current dir? Output?

**Comment by varunagrawal** [comment]
Sorry. That was a typo. I just checked and I use the .jar suffix. Output is just the usage instructions.

**Comment by varunagrawal** [comment]
Is this project being maintained? It's been almost a month since PR #145 and I still don't see an update to the tool.

**Comment by javabrett** [comment]
@varunagrawal Please post the entire output either here or as a gist.
