### ISSUE TITLE
strip-blobs-with-ids and .REMOVED.git-id

### ISSUE THREAD

**Issue by suniala** [rtyley/bfg-repo-cleaner#51]
Running BFG with strip-blobs-with-ids does not seem to produce the "*.REMOVED.git-id" placeholder files. Apparently this is a feature (see https://github.com/rtyley/bfg-repo-cleaner/issues/11#issuecomment-14588092). 

Would it be possible to have BFG produce the placeholder files even when using strip-blobs-with-ids?

Some background. I do not know what the official purpose of these placeholder files is but I have found them useful in three ways:
1. In case a build of an old version fails due to an accidentally removed historical file, I can immediately see which file is missing and why.
2. After running BFG, I can quickly verify that a given historical version (i.e. tag) includes all the relevant files (do a checkout followed by `find . -name "*REMOVED*"`, for example).
3. I may even list every file that ever existed in the repo and was consequently removed by BFG (e.g. `git rev-list HEAD | xargs -L 1 git ls-tree -r | grep REMOVED`).

**Comment by jhabdas** [comment]
To dig a dead horse and beat it a little... What would it take to keep the current default behavior and add a CLI flag to drop in the placeholder files? In my use case I'm using BFG to strip out some files. Those _some files_ were determined by an ETL operation whereby I sent as many files as I could up to a cloud service until it ran out of available space. now I need to collect the blob ids of those files so I can selectively remove them with BFG (or so I think).

Assuming I can get the blob ids and pass them to the `--strip-blobs-with-ids` flag, knowing about the placeholder files and the possibility of using them gives me a warm fuzzy.

What if another CLI flag was implemented to modify the default behavior and output the files when explicitly requested?

**Comment by jhabdas** [comment]
@suniala could you take a look at #53 and give it an emoji if it meets your needs?

**Comment by jhabdas** [comment]
@suniala could you take a look at #218 and give it an emoji if it meets your needs?

**Comment by suniala** [comment]
@jhabdas, thanks for asking. To be honest, I haven't needed BFG in three years. I believe it is best if I don't participate in voting on features I probably will not need in the near future either.

**Comment by suniala** [comment]
I will close this now as there has not been any interest in this issue in almost three years.

**Comment by javabrett** [comment]
Possible that my #112 partly duplicates this.  See also #111 and #140.
