### ISSUE TITLE
Unable to replace text in a large file

### ISSUE THREAD

**Issue by sagerg** [rtyley/bfg-repo-cleaner#513]
When I run `replace-text passwords.txt`, I get expected results for all files in my git history _except_ for 1 file which has around 700,000 lines of text in it. It is named `foo.out` and uses json formatting. I tried isolating the issue by copying the password in another file with about 20 lines of text with similar formatting. The replace text operation worked on that file, but not on the larger file. Any ideas? Thanks!

**Comment by rtyley** [comment]
If you run `bfg` with no command line arguments, it prints out help on all of it's command-line options - including this one:

```
  -fs, --filter-content-size-threshold <size>
                           only do file-content filtering on files smaller than <size> (default is 1048576 bytes)
```

Your 700,000 line file is probably bigger than 1MB, is that right?

**Comment by sagerg** [comment]
@rtyley hello! yes it is, thank you I didn’t notice that default value

**Comment by sagerg** [comment]
Works now! Ran `bfg -rt keys.txt --no-blob-protection -fs 25000000B` to take care of large json files that were littered with passwords. Thanks!
