### ISSUE TITLE
Download link on the homepage is broken

### ISSUE THREAD

**Issue by wereHamster** [rtyley/bfg-repo-cleaner#59]
The link on the homepage points to https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.madgag&a=bfg&v=LATEST, but that URL requires authentication (the server says: Sonatype Nexus Repository Manager API).

**Comment by derangedhk417** [comment]
The link is broken again. I'm getting 502 bad gateway and 504 gateway timeout (randomly one or the other). Using Firefox, JavaScript on, no weird plugins.
