### ISSUE TITLE
General Question:  Starting with a bloated production repo, cleaned up, now what?

### ISSUE THREAD

**Issue by ijames** [rtyley/bfg-repo-cleaner#64]
Perhaps this is an obvious question but perhaps it will lead to some more documentation.

I've followed the steps but the question is what happens after the push.

I've got a clone of the repo in production.  Since the HEAD is protected, does that mean that in principle, after pushing, a pull into prod will do nothing and can I straight from there push back?  

Or will I run into trouble if I make hot production mods to push up to the repo?  (It's a very ancient project with lots of bad practices cooked in.)

Thanks!

**Comment by rtyley** [comment]
Hi @ijames - since this a general question rather than a bug, would you mind asking the question on [stackoverflow.com](http://stackoverflow.com/questions/ask) ? If you tag it with the [`git-rewrite-history`](http://stackoverflow.com/questions/tagged/git-rewrite-history) tag I'll see it.

**Comment by ijames** [comment]
Done, Thanks!  I hope this provides the scope to get a quick easy answer.  http://stackoverflow.com/questions/27734385/replacing-the-prod-repo-after-rewriting-git-history
