### ISSUE TITLE
bfg not working in zsh

### ISSUE THREAD

**Issue by truebit** [rtyley/bfg-repo-cleaner#66]
in `oh-my-zsh` configed `zsh` environment, running 

    java -jar ~/Downloads/bfg-1.12.0.jar --delete-files *.zip `pwd`/portal.git
exited with `zsh: no matches found: *.zip`

change back to `bash`, it works.

**Comment by louim** [comment]
Probably because zsh is trying to [glob](http://en.wikipedia.org/wiki/Glob_%28programming%29) your pattern.

Try it with: `noglob java -jar ~/Downloads/bfg-1.12.0.jar --delete-files *.zip `pwd`/portal.git`

**Comment by truebit** [comment]
@louim Thanks, it works:)
Maybe you should mention it somewhre in documents
