### ISSUE TITLE
for latest release, `java -jar bfg.jar` did not work for me

### ISSUE THREAD

**Issue by allenwlee** [rtyley/bfg-repo-cleaner#76]
`java -jar bfg-1.12.0.jar` did work for me

**Comment by rtyley** [comment]
The jar file name is versioned to help distinguish the different versions, but in examples I just use `bfg.jar`  to avoid having to update the multitude of examples, and for brevity.

Sorry to hear this caused confusion for you, I'll bear it in mind.

**Comment by ellisifnygaard** [comment]
I stumbled into the same trap just now 🙃 It would have been helpful it this were mentioned [in the instructions](https://rtyley.github.io/bfg-repo-cleaner/) 😅
