### ISSUE TITLE
Delete-files with spaces doesn't work

### ISSUE THREAD

**Issue by jpeg729** [rtyley/bfg-repo-cleaner#81]
```
$ bfg --delete-files my\ image.jpg
bfg 1.12.2
Usage: bfg [options] [<repo>]
  ...
Aborting : image.jpg is not a valid Git repository.
```

## Partial workaround
Replace spaces with question marks.
`$ bfg --delete-files my?image.jpg`

BUT that will also delete `my-image.jpg`, `my_image.jpg` `myFimage.jpg` etc.

**Comment by rtyley** [comment]
Which command line shell are you using? Escaping strategies vary by shell.

**Comment by jpeg729** [comment]
Good point.
bfg is a bash script containing
`java -jar /home/mpage/bin/bfg-1.12.2.jar $@`

So naturally, it didn't work.
